# Import Libs

In [254]:
import pandas as pd
import os
from ydata_profiling import ProfileReport

# Set Data File Paths

In [255]:
based_path = "../../dataset/data_combination/"

a1_questionnaire_cohort1_baseline = ""
a2_questionnaire_cohort1_y1 = ""
a3_questionnaire_cohort1_y2 = ""

a4_questionnaire_cohort2_baseline = based_path +  "A4_Questionnaire_Cohort2_Baseline.csv"
a5_questionnaire_cohort2_m1 = ""
a6_questionnaire_cohort2_m3 = ""
a7_questionnaire_cohort2_m6 = ""
a8_questionnaire_cohort2_y1 = ""

b1_sample_collection_form_cohort1_baseline = ""
b2_sample_collection_form_cohort1_y1 = ""
b3_sample_collection_form_cohort1_y2 = ""

b4_sample_collection_form_cohort2_baseline =  based_path + "B4_Sample_Collection_Form_Cohort2_Baseline.csv"
b5_sample_collection_form_cohort2_m1 = based_path + "B5_Sample_Collection_Form_Cohort2_M1.csv"
b6_sample_collection_form_cohort2_m3 = based_path + "B6_Sample_Collection_Form_Cohort2_M3.csv"
b7_sample_collection_form_cohort2_m6 = based_path + "B7_Sample_Collection_Form_Cohort2_M6.csv"
b8_sample_collection_form_cohort2_y1 = based_path + ""

c1_lab_result_cohort1_baseline_elisa = ""
c2_lab_result_cohort1_y1_elisa = ""
c3_lab_result_cohort1_y2_elisa = ""

c4_lab_result_cohort2_baseline_elisa = based_path + "C4_LabResult_Cohort2_Baseline_ELISA.csv"
c5_lab_result_cohort2_baseline_qiastat_pcr = based_path + "C5_LabResult_Cohort2_Baseline_QIASTAT_PCR.csv"
c6_lab_result_cohort2_baseline_ipc_genxpert = based_path + "C6_LabResult_Cohort2_Baseline_ IPC_GenXpert.csv"
c7_lab_result_cohort2_baseline_ipc_tb_culture = based_path + "C7_LabResult_Cohort2_Baseline_IPC_TB_Culture.csv"
c8_lab_result_cohort2_m1_elisa = based_path + "C8_LabResult_Cohort2_M1_ELISA.csv"

c9a_lab_result_pdf_ipc_genxpert = ""
c9b_lab_result_pdf_ipc_tb_culture = ""

d1_screening_form_cohort1_baseline = ""
d2_screening_form_cohort1_y1 = ""
d3_screening_form_cohort1_y2 = ""

d4_screening_form_cohort2_baseline = based_path + "C4_LabResult_Cohort2_Baseline_ELISA.csv"
d5_screening_form_cohort2_m1 = ""
d6_screening_form_cohort2_m3 = ""
d7_screening_form_cohort2_m6 = ""
d8_screening_form_cohort2_y1 = ""

# Read Datasets

In [256]:
b4_df = pd.read_csv(b4_sample_collection_form_cohort2_baseline)
b5_df = pd.read_csv(b5_sample_collection_form_cohort2_m1)
b6_df = pd.read_csv(b6_sample_collection_form_cohort2_m3)
b7_df = pd.read_csv(b7_sample_collection_form_cohort2_m6)

c4_df = pd.read_csv(c4_lab_result_cohort2_baseline_elisa)
c5_df = pd.read_csv(c5_lab_result_cohort2_baseline_qiastat_pcr)
c6_df = pd.read_csv(c6_lab_result_cohort2_baseline_ipc_genxpert)
c7_df = pd.read_csv(c7_lab_result_cohort2_baseline_ipc_tb_culture)
c8_df = pd.read_csv(c8_lab_result_cohort2_m1_elisa)

In [257]:
# fill A1 by A1manual for each dataset and drop unnecessary column
b4_df['A1'] = b4_df['A1'].fillna(b4_df['A1manual'])
b4_df = b4_df.drop(columns=['FormVersion', 'instanceName', 'Status', 'DeviceID', 'AttachmentsExpected', 'ReviewState', 'instanceID', 'A1manual', 'KEY'])

b5_df['A1'] = b5_df['A1'].fillna(b5_df['A1manual'])
b5_df = b5_df.drop(columns=['FormVersion', 'instanceName', 'Status', 'DeviceID', 'AttachmentsExpected', 'ReviewState', 'instanceID', 'A1manual', 'KEY'])

b6_df['A1'] = b6_df['A1'].fillna(b6_df['A1manual'])
b6_df = b6_df.drop(columns=['FormVersion', 'instanceName', 'Status', 'DeviceID', 'AttachmentsExpected', 'ReviewState', 'instanceID', 'A1manual', 'KEY'])

b7_df['A1'] = b7_df['A1'].fillna(b7_df['A1manual'])
b7_df = b7_df.drop(columns=['FormVersion', 'instanceName', 'Status', 'DeviceID', 'AttachmentsExpected', 'ReviewState', 'instanceID', 'A1manual', 'KEY'])



c4_df['A1'] = c4_df['A1'].fillna(c4_df['A1manual'])
c4_df = c4_df.drop(columns=['FormVersion', 'instanceName', 'Status', 'DeviceID', 'AttachmentsExpected', 'ReviewState', 'instanceID', 'A1manual', 'KEY'])

c5_df['A1'] = c5_df['A1'].fillna(c5_df['A1manual'])
c5_df = c5_df.drop(columns=['FormVersion', 'instanceName', 'Status', 'DeviceID', 'AttachmentsExpected', 'ReviewState', 'instanceID', 'A1manual', 'KEY'])

c6_df['A1'] = c6_df['A1'].fillna(c6_df['A1manual'])
c6_df = c6_df.drop(columns=['FormVersion', 'instanceName', 'Status', 'DeviceID', 'AttachmentsExpected', 'ReviewState', 'instanceID', 'A1manual', 'KEY'])

c7_df['A1'] = c7_df['A1'].fillna(c7_df['A1manual'])
c7_df = c7_df.drop(columns=['FormVersion', 'instanceName', 'Status', 'DeviceID', 'AttachmentsExpected', 'ReviewState', 'instanceID', 'A1manual', 'KEY'])

c8_df['A1'] = c8_df['A1'].fillna(c8_df['A1manual'])
c8_df = c8_df.drop(columns=['FormVersion', 'instanceName', 'Status', 'DeviceID', 'AttachmentsExpected', 'ReviewState', 'instanceID', 'A1manual', 'KEY'])

In [258]:
# check the same column in all dataframe
common_columns = (
    set(b4_df.columns) & set(b5_df.columns) & set(b6_df.columns) & set(b7_df.columns)

    & set(c4_df.columns) & set(c5_df.columns) & set(c6_df.columns) & set(c7_df.columns) & set(c8_df.columns)
)

for col in common_columns:
    print(col)

SubmitterName
SubmissionDate
A1m_cal
I1d
A1
n_A1m
I4d
Edits
SubmitterID
I5u
A2
A1m_s
I2s
I3e
AttachmentsPresent

In [259]:
# rename column name based on form name, except A1 (patient ID)
b4_df = b4_df.add_prefix("B4_").rename(columns={"B4_A1":"A1"})
b5_df = b5_df.add_prefix("B5_").rename(columns={"B5_A1":"A1"})
b6_df = b6_df.add_prefix("B6_").rename(columns={"B6_A1":"A1"})
b7_df = b7_df.add_prefix("B7_").rename(columns={"B7_A1":"A1"})

c4_df = c4_df.add_prefix("C4_").rename(columns={"C4_A1":"A1"})
c5_df = c5_df.add_prefix("C5_").rename(columns={"C5_A1":"A1"})
c6_df = c6_df.add_prefix("C6_").rename(columns={"C6_A1":"A1"})
c7_df = c7_df.add_prefix("C7_").rename(columns={"C7_A1":"A1"})
c8_df = c8_df.add_prefix("C8_").rename(columns={"C8_A1":"A1"})

In [260]:
print("B4:", b4_df.shape)
print("B5:", b5_df.shape)
print("B6:", b6_df.shape)
print("B7:", b7_df.shape)

print("C4:", c4_df.shape)
print("C5:", c5_df.shape)
print("C6:", c6_df.shape)
print("C7:", c7_df.shape)
print("C8:", c8_df.shape)

total_columns = (
    b4_df.shape[1] + b5_df.shape[1] + b6_df.shape[1] + b7_df.shape[1] + c4_df.shape[1] + c5_df.shape[1] + c6_df.shape[1] + c7_df.shape[1] + c8_df.shape[1]
)
print("Total Columns:", total_columns)

B4: (227, 39)
B5: (159, 24)
B6: (4, 24)
B7: (1, 24)
C4: (232, 83)
C5: (207, 110)
C6: (204, 24)
C7: (135, 29)
C8: (29, 61)
Total Columns: 418

In [261]:
b4_df['A1'].nunique()

225

## Start merging dataframes

In [262]:
merged_df = pd.merge(b4_df, b5_df, on="A1", how="left")
merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,B5_A3,B5_A4,B5_A5,B5_A6,B5_cal_A6,B5_A7,B5_SubmitterID,B5_SubmitterName,B5_AttachmentsPresent,B5_Edits
0,2026-07-03T10:31:21.603Z,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03T09:56:51.877Z,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03T06:55:09.383Z,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-03T06:52:54.780Z,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-02T02:59:58.702Z,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,2025-12-04T07:28:51.586Z,2025-12-04,2025-12-04T10:28:40.846+07:00,2025-12-04T14:28:51.101+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0006,NaN,NaN,NaN,...,1.0,4.0,Len,14:13,14:13:00.000+07:00,NaN,157.0,T02,0.0,0.0
225,2025-12-03T10:13:32.979Z,2025-12-03,2025-12-03T17:07:57.288+07:00,2025-12-03T17:13:32.361+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0005,NaN,NaN,NaN,...,1.0,5.0,Ya,09:29,09:29:00.000+07:00,NaN,157.0,T02,0.0,0.0
226,2025-12-03T03:12:33.723Z,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,1.0,5.0,Horng,10:15,10:15:00.000+07:00,NaN,157.0,T02,0.0,0.0
228,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,1.0,5.0,Horng,08:53,08:53:00.000+07:00,NaN,157.0,T02,0.0,0.0

In [263]:
merged_df = pd.merge(merged_df, b6_df, on="A1", how="left")
merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,B6_A3,B6_A4,B6_A5,B6_A6,B6_cal_A6,B6_A7,B6_SubmitterID,B6_SubmitterName,B6_AttachmentsPresent,B6_Edits
0,2026-07-03T10:31:21.603Z,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03T09:56:51.877Z,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03T06:55:09.383Z,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-03T06:52:54.780Z,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-02T02:59:58.702Z,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,2025-12-04T07:28:51.586Z,2025-12-04,2025-12-04T10:28:40.846+07:00,2025-12-04T14:28:51.101+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0006,NaN,NaN,NaN,...,1.0,5.0,Touch,11,NaN,15.0,157.0,T02,0.0,0.0
225,2025-12-03T10:13:32.979Z,2025-12-03,2025-12-03T17:07:57.288+07:00,2025-12-03T17:13:32.361+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0005,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,2025-12-03T03:12:33.723Z,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [264]:
merged_df = pd.merge(merged_df, b7_df, on="A1", how="left")
merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,B7_A3,B7_A4,B7_A5,B7_A6,B7_cal_A6,B7_A7,B7_SubmitterID,B7_SubmitterName,B7_AttachmentsPresent,B7_Edits
0,2026-07-03T10:31:21.603Z,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03T09:56:51.877Z,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03T06:55:09.383Z,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-03T06:52:54.780Z,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-02T02:59:58.702Z,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,2025-12-04T07:28:51.586Z,2025-12-04,2025-12-04T10:28:40.846+07:00,2025-12-04T14:28:51.101+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0006,NaN,NaN,NaN,...,1.0,5.0,Channy,14:30,14:30:00.000+07:00,NaN,156.0,T01,0.0,0.0
225,2025-12-03T10:13:32.979Z,2025-12-03,2025-12-03T17:07:57.288+07:00,2025-12-03T17:13:32.361+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0005,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,2025-12-03T03:12:33.723Z,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [265]:
merged_df = pd.merge(merged_df, c4_df, on="A1", how="left")
merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,C4_C4_2,C4_C4_3,C4_C4_4,C4_C4_5,C4_C4_5r,C4_D1,C4_SubmitterID,C4_SubmitterName,C4_AttachmentsPresent,C4_Edits
0,2026-07-03T10:31:21.603Z,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03T09:56:51.877Z,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03T06:55:09.383Z,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-03T06:52:54.780Z,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-02T02:59:58.702Z,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,2025-12-03T03:12:33.723Z,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,1.0,T16,L01,2.0,NaN,- No detection of anti-DENV IgM in CSF and in ...,171.0,T16,0.0,0.0
243,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,1.0,T15,L01,1.0,NaN,- Detection of anti-flavivirus IgG.,170.0,T15,0.0,0.0
244,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,1.0,T16,L01,1.0,NaN,""" - No detection of anti-DENV IgM in CSF and i...",171.0,T16,0.0,0.0
245,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,- Detection of anti-DENV IgM in acute serum. I...,170.0,T15,0.0,0.0
246,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,2.0,T16,L02,2.0,NaN,""" - No detection of anti-DENV IgM in CSF - Ind...",171.0,T16,0.0,0.0

In [266]:
merged_df = pd.merge(merged_df, c5_df, on="A1", how="left")
merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,C5_C2_9ct,C5_C2_10,C5_C2_10ct,C5_C2_8,C5_C2_8ct,C5_D1,C5_SubmitterID,C5_SubmitterName,C5_AttachmentsPresent,C5_Edits
0,2026-07-03T10:31:21.603Z,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03T09:56:51.877Z,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03T06:55:09.383Z,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-03T06:52:54.780Z,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-02T02:59:58.702Z,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2025-12-03T03:12:33.723Z,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,Pathogen is NOT DETECTED,170.0,T15,0.0,0.0
246,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,Pathogen is NOT DETECTED,170.0,T15,0.0,0.0
247,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,Pathogen is NOT DETECTED,170.0,T15,0.0,0.0
248,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,Pathogen is NOT DETECTED,170.0,T15,0.0,0.0
249,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,Pathogen is NOT DETECTED,170.0,T15,0.0,0.0

In [267]:
merged_df = pd.merge(merged_df, c6_df, on="A1", how="left")
merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,C6_A6,C6_A7,C6_A8,C6_A9,C6_B1,C6_B2,C6_SubmitterID,C6_SubmitterName,C6_AttachmentsPresent,C6_Edits
0,2026-07-03T10:31:21.603Z,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03T09:56:51.877Z,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03T06:55:09.383Z,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,T17,SITH Charya,CSF,2026-07-04,6.0,NaN,172.0,T17,0.0,0.0
3,2026-07-03T06:52:54.780Z,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,T17,SITH Charya,CSF,2026-07-04,6.0,NaN,172.0,T17,0.0,0.0
4,2026-07-02T02:59:58.702Z,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,2025-12-03T03:12:33.723Z,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,T17,Dr. NOP Puthea,CSF,2025-12-03,6.0,NaN,172.0,T17,0.0,0.0
249,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,T17,Dr. NOP Puhea\n,CSF,2025-11-27,6.0,NaN,172.0,T17,0.0,0.0
250,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,T17,Dr. NOP Puhea\n,CSF,2025-11-27,6.0,NaN,172.0,T17,0.0,0.0
251,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,T17,Dr. SITH Charya,CSF,2025-11-25,6.0,NaN,172.0,T17,0.0,0.0
252,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,T17,Dr. SITH Charya,CSF,2025-11-25,6.0,NaN,172.0,T17,0.0,0.0

In [268]:
merged_df = pd.merge(merged_df, c7_df, on="A1", how="left")
merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,C7_B2,C7_B2other,C7_B3,C7_B3other,C7_C1,C7_C2,C7_SubmitterID,C7_SubmitterName,C7_AttachmentsPresent,C7_Edits
0,2026-07-03T10:31:21.603Z,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03T09:56:51.877Z,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03T06:55:09.383Z,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-03T06:52:54.780Z,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-02T02:59:58.702Z,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,2025-12-03T03:12:33.723Z,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,172.0,T17,0.0,0.0
249,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,172.0,T17,0.0,0.0
250,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,172.0,T17,0.0,0.0
251,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,172.0,T17,0.0,0.0
252,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,172.0,T17,0.0,0.0

In [269]:
merged_df = pd.merge(merged_df, c8_df, on="A1", how="left")
merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,C8_B4_2,C8_B4_3,C8_B4_4,C8_B4_5,C8_B4_5r,C8_C1,C8_SubmitterID,C8_SubmitterName,C8_AttachmentsPresent,C8_Edits
0,2026-07-03T10:31:21.603Z,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03T09:56:51.877Z,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03T06:55:09.383Z,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-03T06:52:54.780Z,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-02T02:59:58.702Z,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,2025-12-03T03:12:33.723Z,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,1.0,T15,L01,1.0,NaN,- Detection of anti-DENV IgM in acute and conv...,170.0,T15,0.0,0.0
250,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,1.0,T15,L01,1.0,NaN,- Detection of anti-DENV IgM in acute and conv...,170.0,T15,0.0,0.0
251,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,- Detection of anti-flavivirus IgM in convales...,170.0,T15,0.0,0.0
252,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,- Detection of anti-flavivirus IgM in convales...,170.0,T15,0.0,0.0

In [270]:
duplicate_df = merged_df[
    merged_df.groupby('A1')['A1'].transform('count') > 1
]

duplicate_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,C8_B4_2,C8_B4_3,C8_B4_4,C8_B4_5,C8_B4_5r,C8_C1,C8_SubmitterID,C8_SubmitterName,C8_AttachmentsPresent,C8_Edits
26,2026-06-09T10:09:44.005Z,2026-06-09,2026-06-09T17:09:06.085+07:00,2026-06-09T17:09:43.265+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0044,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2026-06-09T10:09:44.005Z,2026-06-09,2026-06-09T17:09:06.085+07:00,2026-06-09T17:09:43.265+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0044,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2026-06-04T07:56:16.947Z,2026-06-04,2026-06-04T14:52:58.879+07:00,2026-06-04T14:56:16.181+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0041,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2026-06-04T07:56:16.947Z,2026-06-04,2026-06-04T14:52:58.879+07:00,2026-06-04T14:56:16.181+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0041,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2026-06-03T04:40:53.522Z,2026-06-03,2026-06-03T11:40:04.845+07:00,2026-06-03T11:40:52.800+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0038,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2026-06-03T04:40:53.522Z,2026-06-03,2026-06-03T11:40:04.845+07:00,2026-06-03T11:40:52.800+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0038,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,2026-05-18T09:41:29.051Z,2026-05-18,2026-05-18T16:39:28.542+07:00,2026-05-18T16:41:28.603+07:00,collect:HWmr5IpdBFgGHeiN,T03,DEM2-SR-0028,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,2026-05-18T09:41:29.051Z,2026-05-18,2026-05-18T16:39:28.542+07:00,2026-05-18T16:41:28.603+07:00,collect:HWmr5IpdBFgGHeiN,T03,DEM2-SR-0028,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,2026-05-18T09:40:49.382Z,2026-05-18,2026-05-18T16:39:15.099+07:00,2026-05-18T16:40:48.684+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0128,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,2026-05-18T09:40:49.382Z,2026-05-18,2026-05-18T16:39:15.099+07:00,2026-05-18T16:40:48.684+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0128,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,2026-05-18T03:07:33.099Z,2026-05-18,2026-05-18T09:52:35.764+07:00,2026-05-18T10:07:32.624+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0126,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,2026-05-18T03:07:33.099Z,2026-05-18,2026-05-18T09:52:35.764+07:00,2026-05-18T10:07:32.624+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0126,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,2026-05-18T02:50:26.342Z,2026-05-18,2026-05-18T09:49:27.528+07:00,2026-05-18T09:50:25.668+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0127,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,2026-05-18T02:50:26.342Z,2026-05-18,2026-05-18T09:49:27.528+07:00,2026-05-18T09:50:25.668+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0127,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,2026-05-11T09:57:52.135Z,2026-05-11,2026-05-11T14:37:04.474+07:00,2026-05-11T16:57:51.581+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0026,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,2026-05-11T09:57:52.135Z,2026-05-11,2026-05-11T14:37:04.474+07:00,2026-05-11T16:57:51.581+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0026,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,2026-05-11T09:57:52.135Z,2026-05-11,2026-05-11T14:37:04.474+07:00,2026-05-11T16:57:51.581+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0026,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,2026-05-11T09:57:52.135Z,2026-05-11,2026-05-11T14:37:04.474+07:00,2026-05-11T16:57:51.581+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0026,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,2026-05-11T03:57:43.218Z,2026-05-11,2026-05-11T09:45:11.140+07:00,2026-05-11T10:57:42.954+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0125,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,2026-05-11T03:57:43.218Z,2026-05-11,2026-05-11T09:45:11.140+07:00,2026-05-11T10:57:42.954+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0125,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2026-05-08T04:32:23.459Z,2026-05-08,2026-05-08T10:56:56.962+07:00,2026-05-08T11:32:23.024+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0124,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,2026-05-08T04:32:23.459Z,2026-05-08,2026-05-08T10:56:56.962+07:00,2026-05-08T11:32:23.024+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0124,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,2026-05-06T01:21:22.723Z,2026-05-06,2026-05-06T08:20:23.355+07:00,2026-05-06T08:21:21.798+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0027,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,2026-05-06T01:21:22.723Z,2026-05-06,2026-05-06T08:20:23.355+07:00,2026-05-06T08:21:21.798+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0027,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,2026-05-04T04:00:28.856Z,2026-05-04,2026-05-04T10:58:58.017+07:00,2026-05-04T11:00:28.286+07:00,collect:HWmr5IpdBFgGHeiN,T03,DEM2-SR-0025,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,2026-05-04T04:00:28.856Z,2026-05-04,2026-05-04T10:58:58.017+07:00,2026-05-04T11:00:28.286+07:00,collect:HWmr5IpdBFgGHeiN,T03,DEM2-SR-0025,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2026-05-04T03:37:29.828Z,2026-05-04,2026-05-04T09:28:20.931+07:00,2026-05-04T10:37:29.319+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0118,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,2026-05-04T03:37:29.828Z,2026-05-04,2026-05-04T09:28:20.931+07:00,2026-05-04T10:37:29.319+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0118,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,2026-04-29T03:15:05.620Z,2026-04-29,2026-04-29T09:51:22.163+07:00,2026-04-29T10:15:04.754+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0114,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,2026-04-29T03:15:05.620Z,2026-04-29,2026-04-29T09:51:22.163+07:00,2026-04-29T10:15:04.754+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0114,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,2026-04-22T08:56:02.230Z,2026-04-22,2026-04-22T15:32:03.372+07:00,2026-04-22T15:33:11.362+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0020,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,2026-04-22T08:56:02.230Z,2026-04-22,2026-04-22T15:32:03.372+07:00,2026-04-22T15:33:11.362+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0020,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,2026-04-06T08:06:00.652Z,2026-04-06,2026-04-06T15:02:41.866+07:00,2026-04-06T15:05:59.936+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0016,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,2026-04-06T08:06:00.652Z,2026-04-06,2026-04-06T15:02:41.866+07:00,2026-04-06T15:05:59.936+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0016,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,2026-03-20T01:48:43.662Z,2026-03-20,2026-03-20T08:44:22.073+07:00,2026-03-20T08:48:42.416+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,2026-03-20T01:48:43.662Z,2026-03-20,2026-03-20T08:44:22.073+07:00,2026-03-20T08:48:42.416+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,2026-03-19T10:18:16.857Z,2026-03-19,2026-03-19T17:17:07.118+07:00,2026-03-19T17:18:16.377+07:00,collect:RQ1eyOTTgb72DTff,T12,DEM2-SR-0010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2026-03-19T10:18:16.857Z,2026-03-19,2026-03-19T17:17:07.118+07:00,2026-03-19T17:18:16.377+07:00,collect:RQ1eyOTTgb72DTff,T12,DEM2-SR-0010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,2026-03-18T09:21:19.381Z,2026-03-18,2026-03-18T16:19:33.906+07:00,2026-03-18T16:21:18.630+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0073,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,2026-03-18T09:21:19.381Z,2026-03-18,2026-03-18T16:19:33.906+07:00,2026-03-18T16:21:18.630+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0073,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,2026-03-11T02:51:04.816Z,2026-03-11,2026-03-11T09:47:24.149+07:00,2026-03-11T09:51:04.363+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0006,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,2026-03-10T05:27:22.264Z,2026-03-10,2026-03-10T12:25:56.447+07:00,2026-03-10T12:27:21.828+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0006,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,2026-02-12T03:50:54.537Z,2026-02-12,2026-02-12T10:47:19.229+07:00,2026-02-12T10:50:53.630+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0055,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,2026-02-12T03:50:54.537Z,2026-02-12,2026-02-12T10:47:19.229+07:00,2026-02-12T10:50:53.630+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0055,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,2025-12-05T07:10:54.152Z,2025-12-05,2025-12-05T14:07:51.993+07:00,2025-12-05T14:10:53.567+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0007,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,2025-12-05T07:10:54.152Z,2025-12-05,2025-12-05T14:07:51.993+07:00,2025-12-05T14:10:53.567+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0007,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,2025-12-04T07:28:51.586Z,2025-12-04,2025-12-04T10:28:40.846+07:00,2025-12-04T14:28:51.101+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0006,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,"anti-JEV IgM positive, anti-DENV IgM positive,...",170.0,T15,0.0,0.0
246,2025-12-04T07:28:51.586Z,2025-12-04,2025-12-04T10:28:40.846+07:00,2025-12-04T14:28:51.101+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0006,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,"anti-JEV IgM positive, anti-DENV IgM positive,...",170.0,T15,0.0,0.0
249,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,1.0,T15,L01,1.0,NaN,- Detection of anti-DENV IgM in acute and conv...,170.0,T15,0.0,0.0
250,2025-11-26T08:33:45.497Z,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,1.0,T15,L01,1.0,NaN,- Detection of anti-DENV IgM in acute and conv...,170.0,T15,0.0,0.0
251,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,- Detection of anti-flavivirus IgM in convales...,170.0,T15,0.0,0.0
252,2025-11-25T02:43:54.762Z,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,- Detection of anti-flavivirus IgM in convales...,170.0,T15,0.0,0.0

## Find duplicates rows and its error

In [271]:
def find_duplicate_differences(df, id_col="A1"):

    result = []

    # only duplicated IDs
    duplicate_ids = df[df[id_col].duplicated(keep=False)][id_col].unique()

    for patient_id in duplicate_ids:

        tmp = df[df[id_col] == patient_id]

        diff_cols = []

        for col in tmp.columns:

            if col == id_col:
                continue

            # count unique values
            if tmp[col].nunique(dropna=False) > 1:
                diff_cols.append(col)

        result.append({
            id_col: patient_id,
            "Different Columns": diff_cols,
            "Number of Differences": len(diff_cols)
        })

    return pd.DataFrame(result)

In [272]:
difference_report = find_duplicate_differences(merged_df)
difference_report

,A1,Different Columns,Number of Differences
0,DEM2-SR-0044,"[C5_SubmissionDate, C5_I1d, C5_I2s, C5_I3e, C5...",49
1,DEM2-SR-0041,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",50
2,DEM2-SR-0038,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",49
3,DEM2-SR-0028,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",46
4,DEM2-PP-0128,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",13
5,DEM2-PP-0126,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",15
6,DEM2-PP-0127,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",16
7,DEM2-SR-0026,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",49
8,DEM2-PP-0125,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",12
9,DEM2-PP-0124,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",12
10,DEM2-SR-0027,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",42
11,DEM2-SR-0025,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",45
12,DEM2-PP-0118,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",15
13,DEM2-PP-0114,"[C6_SubmissionDate, C6_I2s, C6_I3e, C6_A2, C6_A3]",5
14,DEM2-SR-0020,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",43
15,DEM2-SR-0016,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",13
16,DEM2-SR-0010,"[B4_SubmissionDate, B4_I1d, B4_I2s, B4_I3e, B4...",80
17,DEM2-PP-0073,"[B5_SubmissionDate, B5_I2s, B5_I3e, B5_A5, B5_...",6
18,DEM2-SR-0006,"[B4_SubmissionDate, B4_I1d, B4_I2s, B4_I3e, B4...",23
19,DEM2-PP-0055,"[B5_SubmissionDate, B5_I1d, B5_I2s, B5_I3e, B5...",8
20,DEM2-PP-0007,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",14
21,DEM2-PP-0006,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",16
22,DEM2-PP-0002,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",38
23,DEM2-PP-0001,"[C4_SubmissionDate, C4_I1d, C4_I2s, C4_I3e, C4...",37

In [273]:
# convert submission date to datetime
merged_df['B4_SubmissionDate'] = pd.to_datetime(
    merged_df['B4_SubmissionDate'],
    errors='coerce'
)

# sort newest first
merged_df = merged_df.sort_values(
    by='B4_SubmissionDate',
    ascending=False
)

# keep latest record per patient
merged_df = merged_df.drop_duplicates(
    subset='A1',
    keep='first'
)

merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,C8_B4_2,C8_B4_3,C8_B4_4,C8_B4_5,C8_B4_5r,C8_C1,C8_SubmitterID,C8_SubmitterName,C8_AttachmentsPresent,C8_Edits
0,2026-07-03 10:31:21.603000+00:00,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03 09:56:51.877000+00:00,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03 06:55:09.383000+00:00,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-03 06:52:54.780000+00:00,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-02 02:59:58.702000+00:00,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2025-12-04 07:28:51.586000+00:00,2025-12-04,2025-12-04T10:28:40.846+07:00,2025-12-04T14:28:51.101+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0006,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,"anti-JEV IgM positive, anti-DENV IgM positive,...",170.0,T15,0.0,0.0
247,2025-12-03 10:13:32.979000+00:00,2025-12-03,2025-12-03T17:07:57.288+07:00,2025-12-03T17:13:32.361+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0005,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,-No detection of anti-DENV IgM in convalescent...,170.0,T15,0.0,0.0
248,2025-12-03 03:12:33.723000+00:00,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,2025-11-26 08:33:45.497000+00:00,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,1.0,T15,L01,1.0,NaN,- Detection of anti-DENV IgM in acute and conv...,170.0,T15,0.0,0.0
251,2025-11-25 02:43:54.762000+00:00,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,- Detection of anti-flavivirus IgM in convales...,170.0,T15,0.0,0.0

In [274]:
merged_df['C8_C1'].value_counts()

C8_C1
- detection of anti-flavivirus IgM in convalescent serum\n- detection of anti-flavivirus IgG in convalescent serum                                                                                                                                                                                                                                   3
 - detection of anti-flavivirus IgM in convalescent serum\n - detection of anti-flavivirus IgG in convalescent serum                                                                                                                                                                                                                                 3
-No detection of anti-DENV IgM in convalescent serum  \n-No detection of anti-JEV IgM in convalescent serum  \n- No Detection of anti-DENV IgG in convalescent serum    \n-No Detection of anti-JEV IgG in convalescent serum                                                                                                                        2
- detection of anti-DENV IgM in acute and convalescent sera. IgM can persist for months, detection is indicative of current or recent DENV infection.  \n- no detection of anti-JEV IgM in convalescent serum  \n- detection of anti-flavivirus IgG in convalescent serum                                                                            1
  -Detection of anti-DENV IgM only in convalescent serum, DENV infection is likely to be the cause of the disease.\n - No detection of anti-JEV IgM in convalescent serum\n - detection of anti-flavivirus IgG in convalescent seum                                                                                                                  1
- Detection of anti-DENV IgM in acute and convalescent sera. IgM can persist for months, detection is indicative of current or recent DENV infection.\n-No detection of anti-JEV IgM in convalescent serum\n-Detection of anti-flavivirus IgG in convalescent serum                                                                                  1
-No detection of anti-DENV IgM in convalescent serum \n-No detection of anti-JEV IgM in convalescent serum\n-No Detection of anti-DENV IgG in convalescent serum  \n-No Detection of anti-JEV IgG in convalescent serum                                                                                                                              1
anti-JEV IgM positive, anti-DENV IgM positive, and anti-JEV IgG positive by ELISA at one months follow up. \nConclusion: possible JEV infection. To perform the JEV follow-up at 3 months, 6 months and 12 months.                                                                                                                                   1
-detection of anti-DENV IgM in acute and convalescent sera. IgM can persist for months, detection is indicative of current or recent DENV infection.  \n- no detection of anti-JEV IgM in convalescent serum.  \n- detection of anti-flavivirus IgG in convalescent serum                                                                            1
-detection of anti-DENV IgM in acute and convalescent sera. IgM can persist for months, detection is indicative of current or recent DENV infection.  \n-Indeterminate for the detection of anti-JEV IgM in convalescent serum.  \n- No Detection of anti-DENV IgG in convalescent serum    \n-No Detection of anti-JEV IgG in convalescent serum    1
-No detection of anti-DENV IgM in convalescent seru\n-No detection of anti-JEV IgM in convalescent serum\n-Detection of anti-DENV IgG in acute and convalescent sera. IgM can persist for months, detection is indicative of current or recent DENV infection\n-No Detection of anti-JEV IgG in convalescent serum                                   1
-Detection of anti-DENV IgM only in convalescent serum, DENV infection is likely to be the cause of the disease.\n-No detection of anti-JEV IgM in convalescent serum\n-detection of anti-flavivirus IgG in convalescent seum                                                                                                                        1
 -Detection of anti-DENV IgM only in convalescent serum, DENV infection is likely to be the cause of the disease.\n - No detection of anti-JEV IgM in convalescent serum\n - Detection of anti-flavivirus IgG in convalescent seum                                                                                                                   1
-Indeterminate for the detection of anti-DENV IgM in convalescent serum.\n-No detection of anti-JEV IgM in convalescent serum\n-No Detection of anti-DENV IgG in convalescent serum  \n-No Detection of anti-JEV IgG in convalescent serum                                                                                                           1
-Indeterminate for the detection of anti-DENV IgM in convalescebt serum.\n-No detection of anti-JEV IgM in convalescent serum\n-No Detection of anti-DENV IgG in convalescent serum  \n-No Detection of anti-JEV IgG in convalescent serum                                                                                                           1
-Detection of anti-DENV IgM only in convalescent serum, DENV infection is likely to be the cause of the disease.\n-No detection of anti-JEV IgM in convalescent serum\n-No Detection of anti-DENV IgG in convalescent serum  \n-No Detection of anti-JEV IgG in convalescent serum                                                                   1
-No detection of anti-DENV IgM in convalescent serum\n-No detection of anti-JEV IgM in convalescent serum\n-No Detection of anti-DENV IgG in convalescent serum\n-Detection of anti-JEV IgG in acute and convalescent serum. IgG persist many years, detection of IgG alone is not indicative for the current infection.                             1
-Detection of anti-DENV IgM only in convalescent serum, DENV infection is likely to be the cause of the disease.\n-No detection of anti-JEV IgM in convalescent serum\n- Detection of anti-flavivirus IgG in convalescent serum                                                                                                                      1
- No detection of anti-DENV IgM in convalescent serum\n- No detection of anti-JEV IgM in convalescent serum\n- No Detection of anti-DENV IgG in convalescent serum  \n- No Detection of anti-JEV IgG in convalescent serum                                                                                                                           1
- Detection of anti-flavivirus IgM in convalescent serum\n- No Detection of anti-DENV IgG in convalescent serum  \n- No Detection of anti-JEV IgG in convalescent serum                                                                                                                                                                              1
-No detection of anti-DENV IgM in convalescent serum\n-No detection of anti-JEV IgM in convalescent serum\n-Detection of anti-flavivirus IgG in convalescent serum                                                                                                                                                                                   1
-Detection of anti-DENV IgM only in convalescent serum, DENV infection is likely to be the cause of the disease.\n -Indeterminate for the detection of anti-JEV IgM in convalescent serum. \n-No Detection of anti-DENV IgG in convalescent serum  \n-No Detection of anti-JEV IgG in convalescent serum                                             1
-No detection of anti-DENV IgM in convalescent serum\n -No detection of anti-JEV IgM in convalescent serum\n -No Detection of anti-DENV IgG in convalescent serum  \n -No Detection of anti-JEV IgG in convalescent serum                                                                                                                            1
- Detection of anti-flavivirus IgM in convalescent serum\n- No detection of anti-DENV IgG in convalescent serum\n- No detection of anti-JEV IgG in convalescent serum                                                                                                                                                                                1
Name: count, dtype: int64

In [275]:
merged_df

,B4_SubmissionDate,B4_I1d,B4_I2s,B4_I3e,B4_I4d,B4_I5u,A1,B4_A1m_s,B4_A1m_cal,B4_n_A1m,...,C8_B4_2,C8_B4_3,C8_B4_4,C8_B4_5,C8_B4_5r,C8_C1,C8_SubmitterID,C8_SubmitterName,C8_AttachmentsPresent,C8_Edits
0,2026-07-03 10:31:21.603000+00:00,2026-07-03,2026-07-03T17:30:38.458+07:00,2026-07-03T17:31:19.840+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0054,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-03 09:56:51.877000+00:00,2026-07-03,2026-07-03T16:50:42.758+07:00,2026-07-03T16:56:51.012+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0173,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-03 06:55:09.383000+00:00,2026-07-03,2026-07-03T13:53:14.219+07:00,2026-07-03T13:55:08.631+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0172,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-03 06:52:54.780000+00:00,2026-07-03,2026-07-03T13:51:40.767+07:00,2026-07-03T13:52:54.056+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0171,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-02 02:59:58.702000+00:00,2026-07-02,2026-07-02T09:58:42.885+07:00,2026-07-02T09:59:57.948+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2025-12-04 07:28:51.586000+00:00,2025-12-04,2025-12-04T10:28:40.846+07:00,2025-12-04T14:28:51.101+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0006,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,"anti-JEV IgM positive, anti-DENV IgM positive,...",170.0,T15,0.0,0.0
247,2025-12-03 10:13:32.979000+00:00,2025-12-03,2025-12-03T17:07:57.288+07:00,2025-12-03T17:13:32.361+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0005,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,-No detection of anti-DENV IgM in convalescent...,170.0,T15,0.0,0.0
248,2025-12-03 03:12:33.723000+00:00,2025-12-03,2025-12-03T09:26:48.748+07:00,2025-12-03T10:12:33.210+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-PP-0003,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,2025-11-26 08:33:45.497000+00:00,2025-11-26,2025-11-26T15:32:31.534+07:00,2025-11-26T15:33:44.880+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0002,NaN,NaN,NaN,...,1.0,T15,L01,1.0,NaN,- Detection of anti-DENV IgM in acute and conv...,170.0,T15,0.0,0.0
251,2025-11-25 02:43:54.762000+00:00,2025-11-25,2025-11-25T09:32:14.846+07:00,2025-11-25T09:43:54.330+07:00,collect:jcItTlkxdPzoHjMY,T01,DEM2-PP-0001,NaN,NaN,NaN,...,1.0,T15,L01,2.0,NaN,- Detection of anti-flavivirus IgM in convales...,170.0,T15,0.0,0.0

# Columns to be Kept

In [276]:
keep_column_df = pd.read_excel('cohort2_lab_result_column.xlsx')
print(keep_column_df['columns'].tolist())
merged_df = merged_df[keep_column_df['columns'].tolist()]
merged_df

['A1', 'B4_A2l', 'B4_A2s/1', 'B4_A2s/2', 'B4_A2s/3', 'B4_B1', 'B4_C1', 'B4_D1', 'B5_A2l', 'B5_A2d', 'B5_A3', 'B6_A2l', 'B6_A2d', 'B6_A3', 'B7_A2l', 'B7_A2d', 'B7_A3', 'C4_A2', 'C4_A6/1', 'C4_A6/2', 'C4_B1_1', 'C4_B1_2', 'C4_B1_5', 'C4_B1_5r', 'C4_B3_1', 'C4_B3_2', 'C4_B3_5', 'C4_B3_5r', 'C4_C1_1', 'C4_C1_2', 'C4_C1_5', 'C4_C1_5r', 'C4_C2_1', 'C4_C2_2', 'C4_C2_5', 'C4_C2_5r', 'C4_C3_1', 'C4_C3_2', 'C4_C3_5', 'C4_C3_5r', 'C4_C4_1', 'C4_C4_2', 'C4_C4_5', 'C4_C4_5r', 'C5_B1', 'C5_B2', 'C5_B5', 'C5_B5ct', 'C5_B6', 'C5_B6ct', 'C5_B7', 'C5_B7ct', 'C5_B8', 'C5_B8ct', 'C5_B9', 'C5_B9ct', 'C5_B10', 'C5_B10ct', 'C5_B11', 'C5_B11ct', 'C5_B12', 'C5_B12ct', 'C5_B13', 'C5_B13ct', 'C5_B14', 'C5_B14ct', 'C5_B15', 'C5_B15ct', 'C5_B16', 'C5_B16ct', 'C5_B17', 'C5_B17ct', 'C5_B18', 'C5_B18ct', 'C5_B19', 'C5_B19ct', 'C5_C1_1', 'C5_C1_2', 'C5_C1_5', 'C5_C1_5ct', 'C5_C1_6', 'C5_C1_6ct', 'C5_C1_7', 'C5_C1_7ct', 'C5_C1_8', 'C5_C1_8ct', 'C5_C1_9', 'C5_C1_9ct', 'C5_C1_10', 'C5_C1_10ct', 'C5_C2_1', 'C5_C2_2', 'C5_C2_5', 'C5_C2_5ct', 'C5_C2_6', 'C5_C2_6ct', 'C5_C2_7', 'C5_C2_7ct', 'C5_C2_9', 'C5_C2_9ct', 'C5_C2_10', 'C5_C2_10ct', 'C6_A3', 'C6_B1', 'C6_B2', 'C7_A3', 'C7_B1', 'C7_B2', 'C8_A2', 'C8_B1_1', 'C8_B1_2', 'C8_B1_5', 'C8_B1_5r', 'C8_B2_1', 'C8_B2_2', 'C8_B2_5', 'C8_B2_5r', 'C8_B3_1', 'C8_B3_2', 'C8_B3_5', 'C8_B3_5r', 'C8_B4_1', 'C8_B4_2', 'C8_B4_5', 'C8_B4_5r']

,A1,B4_A2l,B4_A2s/1,B4_A2s/2,B4_A2s/3,B4_B1,B4_C1,B4_D1,B5_A2l,B5_A2d,...,C8_B2_5,C8_B2_5r,C8_B3_1,C8_B3_2,C8_B3_5,C8_B3_5r,C8_B4_1,C8_B4_2,C8_B4_5,C8_B4_5r
0,DEM2-SR-0054,2,1,1,1,2026-07-03,2026-07-03,2026-07-03,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DEM2-PP-0173,1,1,1,1,2026-07-03,2026-07-03,2026-07-03,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DEM2-PP-0172,1,1,1,1,2026-07-03,2026-07-03,2026-07-03,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DEM2-PP-0171,1,1,1,1,2026-07-03,2026-07-03,2026-07-03,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DEM2-PP-0170,1,1,1,1,2026-07-02,2026-07-02,2026-07-02,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,DEM2-PP-0006,1,1,1,1,2025-12-04,2025-12-04,2025-12-04,1.0,2026-01-08,...,1.0,NaN,2026-01-12,1.0,1.0,NaN,2026-01-13,1.0,2.0,NaN
247,DEM2-PP-0005,1,1,1,1,2025-12-03,2025-12-03,2025-12-03,1.0,2026-01-02,...,2.0,NaN,2026-01-05,1.0,2.0,NaN,2026-01-06,1.0,2.0,NaN
248,DEM2-PP-0003,1,1,1,1,2025-12-03,2025-12-03,2025-12-03,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,DEM2-PP-0002,1,1,1,1,2025-11-26,2025-11-26,2025-11-26,1.0,2025-12-25,...,1.0,NaN,2025-12-30,1.0,1.0,NaN,2025-12-30,1.0,1.0,NaN
251,DEM2-PP-0001,1,1,1,1,2025-11-25,2025-11-25,2025-11-25,1.0,2025-12-22,...,2.0,NaN,2025-12-30,1.0,1.0,NaN,2025-12-25,1.0,2.0,NaN

# Export Data to CSV (EXCEL)

In [277]:
# combined_df_clean.to_excel('combined_data.xlsx', index=False)
merged_df.to_csv('combined_data.csv')

# Using YDataProfiling to Check Data

In [278]:
# # install first if needed:
# # !pip install ydata-profiling

# profile = ProfileReport(
#     merged_df,
#     title="DEMELE JEV Data Profiling Report",
#     explorative=True
# )

# profile