In [153]:
import pandas as pd
import os

In [ ]:
a1_questionnaire_cohort1_baseline = ""
a2_questionnaire_cohort1_y1 = ""
a3_questionnaire_cohort1_y2 = ""

a4_questionnaire_cohort2_baseline = "../../dataset/data_combination/A4_Questionnaire_Cohort2_Baseline.csv"
a5_questionnaire_cohort2_m1 = ""
a6_questionnaire_cohort2_m3 = ""
a7_questionnaire_cohort2_m6 = ""
a8_questionnaire_cohort2_y1 = ""

b1_sample_collection_form_cohort1_baseline = ""
b2_sample_collection_form_cohort1_y1 = ""
b3_sample_collection_form_cohort1_y2 = ""

b4_sample_collection_form_cohort2_baseline = "../../dataset/data_combination/B4_Sample_Collection_Form_Cohort2_Baseline.csv"
b5_sample_collection_form_cohort2_m1 = "../../dataset/data_combination/"
b6_sample_collection_form_cohort2_m3 = "../../dataset/data_combination/"
b7_sample_collection_form_cohort2_m6 = "../../dataset/data_combination/"
b8_sample_collection_form_cohort2_y1 = "../../dataset/data_combination/"

c1_lab_result_cohort1_baseline_elisa = ""
c2_lab_result_cohort1_y1_elisa = ""
c3_lab_result_cohort1_y2_elisa = ""

c4_lab_result_cohort2_baseline_elisa = "../../dataset/data_combination/B4_Sample_Collection_Form_Cohort2_Baseline.csv"
c5_lab_result_cohort2_baseline_qiastat_pcr = "../../dataset/data_combination/C5_LabResult_Cohort2_Baseline_QIASTAT_PCR.csv"
c6_lab_result_cohort2_baseline_ipc_genxpert = "../../dataset/data_combination/"
c7_lab_result_cohort2_baseline_ipc_tb_culture = "../../dataset/data_combination/"
c8_lab_result_cohort2_m1_elisa = "../../dataset/data_combination/"

c9a_lab_result_pdf_ipc_genxpert = ""
c9b_lab_result_pdf_ipc_tb_culture = ""

d1_screening_form_cohort1_baseline = ""
d2_screening_form_cohort1_y1 = ""
d3_screening_form_cohort1_y2 = ""

d4_screening_form_cohort2_baseline = "../../dataset/data_combination/C4_LabResult_Cohort2_Baseline_ELISA.csv"
d5_screening_form_cohort2_m1 = ""
d6_screening_form_cohort2_m3 = ""
d7_screening_form_cohort2_m6 = ""
d8_screening_form_cohort2_y1 = ""

In [ ]:
d4_df = pd.read_csv(d4_screening_form_cohort2_baseline)

a4_df = pd.read_csv(a4_questionnaire_cohort2_baseline) # exclude for now
b4_df = pd.read_csv(b4_sample_collection_form_cohort2_baseline)
c4_df = pd.read_csv(c4_lab_result_cohort2_baseline_elisa)
c5_df = pd.read_csv(c5_lab_result_cohort2_baseline_qiastat_pcr)

In [156]:
d4_df.head(5)

,SubmissionDate,I1d,I2s,I3e,I4d,I5u,A1,A1manual,A1m_s,A1m_cal,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,2026-06-16T01:13:09.333Z,2026-06-16,2026-06-16T08:09:38.497+07:00,2026-06-16T08:13:08.820+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0042,NaN,NaN,NaN,...,uuid:e5bafd7c-1021-4294-8e34-5f32b567b897,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7
1,2026-06-16T01:09:20.798Z,2026-06-16,2026-06-16T08:04:56.626+07:00,2026-06-16T08:09:20.149+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0041,NaN,NaN,NaN,...,uuid:8d7f6eba-5176-4335-a290-3368fe4268dc,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7
2,2026-06-16T01:04:37.971Z,2026-06-16,2026-06-16T08:01:04.460+07:00,2026-06-16T08:04:37.683+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0040,NaN,NaN,NaN,...,uuid:6cd27a05-d83f-4c6f-b3e2-bdae7b0489fb,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7
3,2026-06-16T00:51:34.675Z,2026-06-16,2026-06-16T07:48:12.641+07:00,2026-06-16T07:51:34.456+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0039,NaN,NaN,NaN,...,uuid:e4703cbc-f332-4878-a018-68db77cf2407,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7
4,2026-06-16T00:47:56.903Z,2026-06-16,2026-06-16T07:44:26.828+07:00,2026-06-16T07:47:56.591+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0038,NaN,NaN,NaN,...,uuid:2ce75ac9-e0ec-4005-b5af-73a0df2aab36,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7

In [157]:
a4_df.head(5)

,SubmissionDate,I1d,I2s,I3e,I4d,I5u,A1,A1manual,A1m_s,A1m_cal,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,2026-06-19T04:25:56.216Z,2026-06-19,2026-06-19T11:21:36.774+07:00,2026-06-19T11:25:55.531+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0034,NaN,NaN,NaN,...,uuid:0c85c2a0-309d-4cbc-998b-45d8b2bac369,166,T11,0,0,NaN,NaN,collect:lM3TOpaH6abwWGtN,0,v27
1,2026-06-19T04:20:59.496Z,2026-06-19,2026-06-19T11:16:46.024+07:00,2026-06-19T11:20:58.759+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0033,NaN,NaN,NaN,...,uuid:66221a96-0f38-44dc-86a8-7d09cbe10c1b,166,T11,0,0,NaN,NaN,collect:lM3TOpaH6abwWGtN,0,v27
2,2026-06-19T04:16:40.027Z,2026-06-19,2026-06-19T11:02:31.658+07:00,2026-06-19T11:16:39.340+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0032,NaN,NaN,NaN,...,uuid:709404af-e980-4222-8cc8-27445e83f78a,166,T11,0,0,NaN,NaN,collect:lM3TOpaH6abwWGtN,0,v27
3,2026-06-19T04:02:28.252Z,2026-06-19,2026-06-19T10:56:39.264+07:00,2026-06-19T11:02:27.608+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0031,NaN,NaN,NaN,...,uuid:55589658-401f-4cf2-80eb-0f40578a49ac,166,T11,0,0,NaN,NaN,collect:lM3TOpaH6abwWGtN,0,v27
4,2026-06-19T03:55:14.360Z,2026-06-19,2026-06-19T10:48:35.703+07:00,2026-06-19T10:55:13.757+07:00,collect:lM3TOpaH6abwWGtN,T11,DEM2-SR-0030,NaN,NaN,NaN,...,uuid:1852ff55-dd80-4b15-a41a-3bf547b3f50f,166,T11,0,0,NaN,NaN,collect:lM3TOpaH6abwWGtN,0,v27

In [158]:
b4_df.head(5)

,SubmissionDate,I1d,I2s,I3e,I4d,I5u,A1,A1manual,A1m_s,A1m_cal,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,2026-06-17T09:39:44.558Z,2026-06-17,2026-06-17T15:55:27.034+07:00,2026-06-17T16:39:44.156+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0162,NaN,NaN,NaN,...,uuid:4787583e-0231-47fe-89b4-0cd34e7e8a9c,157,T02,0,0,NaN,NaN,collect:9qMhME16PHTSvgub,0,v5
1,2026-06-17T08:19:26.623Z,2026-06-17,2026-06-17T15:18:39.974+07:00,2026-06-17T15:19:26.065+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0161,NaN,NaN,NaN,...,uuid:00b8db18-7a3b-41af-818c-8be94bbb5462,157,T02,0,0,NaN,NaN,collect:9qMhME16PHTSvgub,0,v5
2,2026-06-17T04:22:43.459Z,2026-06-17,2026-06-17T11:21:54.613+07:00,2026-06-17T11:22:42.693+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0047,NaN,NaN,NaN,...,uuid:723b85e8-1ead-40f6-9e37-9d06bc173e7d,159,T04,0,0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v5
3,2026-06-16T08:44:40.061Z,2026-06-16,2026-06-16T15:26:56.603+07:00,2026-06-16T15:44:39.542+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0160,NaN,NaN,NaN,...,uuid:d9dfe892-87da-4f79-bc16-1ea9321f1e65,157,T02,0,0,NaN,NaN,collect:9qMhME16PHTSvgub,0,v5
4,2026-06-16T03:47:12.054Z,2026-06-16,2026-06-16T10:45:58.464+07:00,2026-06-16T10:47:11.437+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0159,NaN,NaN,NaN,...,uuid:ac56f0c1-85e5-4e00-a656-330b66de8628,157,T02,0,0,NaN,NaN,collect:9qMhME16PHTSvgub,0,v5

In [159]:
c4_df.head(5)

,SubmissionDate,I1d,I2s,I3e,I4d,I5u,A1,A1manual,A1m_s,A1m_cal,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,2026-06-17T09:39:44.558Z,2026-06-17,2026-06-17T15:55:27.034+07:00,2026-06-17T16:39:44.156+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0162,NaN,NaN,NaN,...,uuid:4787583e-0231-47fe-89b4-0cd34e7e8a9c,157,T02,0,0,NaN,NaN,collect:9qMhME16PHTSvgub,0,v5
1,2026-06-17T08:19:26.623Z,2026-06-17,2026-06-17T15:18:39.974+07:00,2026-06-17T15:19:26.065+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0161,NaN,NaN,NaN,...,uuid:00b8db18-7a3b-41af-818c-8be94bbb5462,157,T02,0,0,NaN,NaN,collect:9qMhME16PHTSvgub,0,v5
2,2026-06-17T04:22:43.459Z,2026-06-17,2026-06-17T11:21:54.613+07:00,2026-06-17T11:22:42.693+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM2-SR-0047,NaN,NaN,NaN,...,uuid:723b85e8-1ead-40f6-9e37-9d06bc173e7d,159,T04,0,0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v5
3,2026-06-16T08:44:40.061Z,2026-06-16,2026-06-16T15:26:56.603+07:00,2026-06-16T15:44:39.542+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0160,NaN,NaN,NaN,...,uuid:d9dfe892-87da-4f79-bc16-1ea9321f1e65,157,T02,0,0,NaN,NaN,collect:9qMhME16PHTSvgub,0,v5
4,2026-06-16T03:47:12.054Z,2026-06-16,2026-06-16T10:45:58.464+07:00,2026-06-16T10:47:11.437+07:00,collect:9qMhME16PHTSvgub,T02,DEM2-PP-0159,NaN,NaN,NaN,...,uuid:ac56f0c1-85e5-4e00-a656-330b66de8628,157,T02,0,0,NaN,NaN,collect:9qMhME16PHTSvgub,0,v5

In [160]:
c5_df.head(5)

,SubmissionDate,I1d,I2s,I3e,I4d,I5u,A1,A1manual,A1m_s,A1m_cal,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,2026-06-17T13:55:06.665Z,2026-06-17,2026-06-17T20:52:34.761+07:00,2026-06-17T20:55:07.123+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-PP-0160,NaN,NaN,NaN,...,uuid:0cab42d8-6419-4d6f-aaaf-ec5d6fc51b81,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7
1,2026-06-17T08:07:12.827Z,2026-06-17,2026-06-17T15:03:46.451+07:00,2026-06-17T15:07:13.164+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-PP-0159,NaN,NaN,NaN,...,uuid:1044a987-aa0c-49e6-a180-dd343d0b8432,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7
2,2026-06-15T10:24:38.098Z,2026-06-15,2026-06-15T17:19:55.844+07:00,2026-06-15T17:24:37.934+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0046,NaN,NaN,NaN,...,uuid:21704e6b-71a3-4193-ae98-a1f95b8948d3,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7
3,2026-06-13T02:06:14.230Z,2026-06-13,2026-06-13T09:03:38.664+07:00,2026-06-13T09:06:15.537+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-PP-0158,NaN,NaN,NaN,...,uuid:7d66b206-309c-418d-a453-8b4f257a898c,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7
4,2026-06-13T02:03:09.350Z,2026-06-13,2026-06-13T09:01:27.899+07:00,2026-06-13T09:03:10.722+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0045,NaN,NaN,NaN,...,uuid:41d51c38-e41d-48ba-ab46-2cfca91ca336,173,T18,0,0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0,v7

In [161]:
merged_df = pd.merge(d4_df, a4_df, on="A1", how="left")
merged_df

,SubmissionDate_x,I1d_x,I2s_x,I3e_x,I4d_x,I5u_x,A1,A1manual_x,A1m_s_x,A1m_cal_x,...,KEY_y,SubmitterID_y,SubmitterName_y,AttachmentsPresent_y,AttachmentsExpected_y,Status_y,ReviewState_y,DeviceID_y,Edits_y,FormVersion_y
0,2026-06-16T01:13:09.333Z,2026-06-16,2026-06-16T08:09:38.497+07:00,2026-06-16T08:13:08.820+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0042,NaN,NaN,NaN,...,uuid:9674332c-e379-43f1-87e7-45bc10ce24e4,167,T12,0,0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0,v27
1,2026-06-16T01:13:09.333Z,2026-06-16,2026-06-16T08:09:38.497+07:00,2026-06-16T08:13:08.820+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0042,NaN,NaN,NaN,...,uuid:7ef1dfca-9350-4d61-a380-bf064678c6eb,158,T03,2,2,NaN,NaN,collect:HWmr5IpdBFgGHeiN,0,v27
2,2026-06-16T01:09:20.798Z,2026-06-16,2026-06-16T08:04:56.626+07:00,2026-06-16T08:09:20.149+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0041,NaN,NaN,NaN,...,uuid:d3f65999-819a-4b9e-af2e-d62ee93550f1,159,T04,0,0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v27
3,2026-06-16T01:04:37.971Z,2026-06-16,2026-06-16T08:01:04.460+07:00,2026-06-16T08:04:37.683+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0040,NaN,NaN,NaN,...,uuid:9e3695e2-3a41-43fb-85a1-c2453c472414,159,T04,2,2,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v27
4,2026-06-16T00:51:34.675Z,2026-06-16,2026-06-16T07:48:12.641+07:00,2026-06-16T07:51:34.456+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0039,NaN,NaN,NaN,...,uuid:eb4b93c5-353c-429a-8c66-8700dc4875c7,159,T04,0,0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,2025-12-28T02:31:27.399Z,2025-12-27,2025-12-27T23:00:19.975+07:00,2025-12-28T09:31:26.109+07:00,collect:1OmvGirXCAZAfOcI,T16,DEM2-PP-0009,NaN,NaN,NaN,...,uuid:755acd8e-9ca9-490b-b2a5-06fd04309b8d,168,T13,0,0,NaN,NaN,collect:IRkZW9JNEG0BHJJg,0,v23
520,2025-12-28T02:29:43.175Z,2025-12-23,2025-12-23T11:20:05.083+07:00,2025-12-28T09:29:42.062+07:00,collect:1OmvGirXCAZAfOcI,T16,NaN,DEM2-PP-0002,DEM2-PP-,2.0,...,uuid:fc1647df-f97c-45a0-a1ff-76ee66456ec6,161,T06,0,0,NaN,NaN,collect:T5QvhN5vxk4nqGua,0,v27
521,2025-12-28T02:29:43.175Z,2025-12-23,2025-12-23T11:20:05.083+07:00,2025-12-28T09:29:42.062+07:00,collect:1OmvGirXCAZAfOcI,T16,NaN,DEM2-PP-0002,DEM2-PP-,2.0,...,uuid:c3e144e6-f10f-4804-a2d8-4b963f8dfe59,161,T06,0,0,NaN,NaN,collect:T5QvhN5vxk4nqGua,0,v24
522,2025-12-28T02:29:32.572Z,2025-12-23,2025-12-23T10:43:02.770+07:00,2025-12-28T09:29:31.072+07:00,collect:1OmvGirXCAZAfOcI,T16,NaN,DEM2-PP-0001,DEM2-PP-,1.0,...,uuid:fc1647df-f97c-45a0-a1ff-76ee66456ec6,161,T06,0,0,NaN,NaN,collect:T5QvhN5vxk4nqGua,0,v27
523,2025-12-28T02:29:32.572Z,2025-12-23,2025-12-23T10:43:02.770+07:00,2025-12-28T09:29:31.072+07:00,collect:1OmvGirXCAZAfOcI,T16,NaN,DEM2-PP-0001,DEM2-PP-,1.0,...,uuid:c3e144e6-f10f-4804-a2d8-4b963f8dfe59,161,T06,0,0,NaN,NaN,collect:T5QvhN5vxk4nqGua,0,v24

In [162]:
merged_df = pd.merge(merged_df, b4_df, on="A1", how="left")
merged_df

,SubmissionDate_x,I1d_x,I2s_x,I3e_x,I4d_x,I5u_x,A1,A1manual_x,A1m_s_x,A1m_cal_x,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,2026-06-16T01:13:09.333Z,2026-06-16,2026-06-16T08:09:38.497+07:00,2026-06-16T08:13:08.820+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0042,NaN,NaN,NaN,...,uuid:3ee39fc1-43c6-4034-ac7e-4656dc96ece8,167.0,T12,0.0,0.0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0.0,v5
1,2026-06-16T01:13:09.333Z,2026-06-16,2026-06-16T08:09:38.497+07:00,2026-06-16T08:13:08.820+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0042,NaN,NaN,NaN,...,uuid:3ee39fc1-43c6-4034-ac7e-4656dc96ece8,167.0,T12,0.0,0.0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0.0,v5
2,2026-06-16T01:09:20.798Z,2026-06-16,2026-06-16T08:04:56.626+07:00,2026-06-16T08:09:20.149+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0041,NaN,NaN,NaN,...,uuid:655736aa-fbc2-4731-ae3e-5f68f20b0533,159.0,T04,0.0,0.0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0.0,v5
3,2026-06-16T01:04:37.971Z,2026-06-16,2026-06-16T08:01:04.460+07:00,2026-06-16T08:04:37.683+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0040,NaN,NaN,NaN,...,uuid:dbebc07f-ead9-4bf8-ba5e-372625adb029,159.0,T04,0.0,0.0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0.0,v5
4,2026-06-16T00:51:34.675Z,2026-06-16,2026-06-16T07:48:12.641+07:00,2026-06-16T07:51:34.456+07:00,collect:jHl2uzO0Hmb0l1o5,T18,DEM2-SR-0039,NaN,NaN,NaN,...,uuid:905e0989-5bb3-43d9-bd17-596084c44235,159.0,T04,0.0,0.0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0.0,v5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,2025-12-28T02:31:27.399Z,2025-12-27,2025-12-27T23:00:19.975+07:00,2025-12-28T09:31:26.109+07:00,collect:1OmvGirXCAZAfOcI,T16,DEM2-PP-0009,NaN,NaN,NaN,...,uuid:6a06a770-5ea7-4036-8786-4cb33d8c8b28,156.0,T01,0.0,0.0,NaN,NaN,collect:jcItTlkxdPzoHjMY,0.0,v5
526,2025-12-28T02:29:43.175Z,2025-12-23,2025-12-23T11:20:05.083+07:00,2025-12-28T09:29:42.062+07:00,collect:1OmvGirXCAZAfOcI,T16,NaN,DEM2-PP-0002,DEM2-PP-,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,2025-12-28T02:29:43.175Z,2025-12-23,2025-12-23T11:20:05.083+07:00,2025-12-28T09:29:42.062+07:00,collect:1OmvGirXCAZAfOcI,T16,NaN,DEM2-PP-0002,DEM2-PP-,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,2025-12-28T02:29:32.572Z,2025-12-23,2025-12-23T10:43:02.770+07:00,2025-12-28T09:29:31.072+07:00,collect:1OmvGirXCAZAfOcI,T16,NaN,DEM2-PP-0001,DEM2-PP-,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,2025-12-28T02:29:32.572Z,2025-12-23,2025-12-23T10:43:02.770+07:00,2025-12-28T09:29:31.072+07:00,collect:1OmvGirXCAZAfOcI,T16,NaN,DEM2-PP-0001,DEM2-PP-,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [163]:
_x = 0 
_y = 0
for col in merged_df.columns:
    # print(col)
    if col.endswith('_x'):
        print(col)
        _x += 1
    if col.endswith('_y'):
        print(col)
        _y += 1

print(_x, _y)

SubmissionDate_x
I1d_x
I2s_x
I3e_x
I4d_x
I5u_x
A1manual_x
A1m_s_x
A1m_cal_x
n_A1m_x
A2_x
A3_x
A6_x
A7_x
A4_x
A5_x
D1_x
instanceID_x
instanceName_x
KEY_x
SubmitterID_x
SubmitterName_x
AttachmentsPresent_x
AttachmentsExpected_x
Status_x
ReviewState_x
DeviceID_x
Edits_x
FormVersion_x
SubmissionDate_y
I1d_y
I2s_y
I3e_y
I4d_y
I5u_y
A1manual_y
A1m_s_y
A1m_cal_y
n_A1m_y
A2_y
A3_y
A4_y
A5_y
A6_y
A7_y
B1_x
B2_x
B3_x
B4_x
B5_x
C2_x
C3_x
C4_x
C5_x
instanceID_y
instanceName_y
KEY_y
SubmitterID_y
SubmitterName_y
AttachmentsPresent_y
AttachmentsExpected_y
Status_y
ReviewState_y
DeviceID_y
Edits_y
FormVersion_y
B1_y
B2_y
B3_y
B4_y
B5_y
C2_y
C3_y
C4_y
C5_y
D1_y
38 38

In [164]:
merged_df = merged_df.loc[
    :,
    ~merged_df.columns.str.endswith('_x')
]

In [165]:
merged_df = pd.merge(merged_df, c4_df, on="A1", how="left")
merged_df = merged_df.loc[
    :,
    ~merged_df.columns.str.endswith('_x')
]
merged_df

,A1,A6/1,A6/2,A8,A9,A10,A11,A1_id,A1_1,A1_2,...,KEY_y,SubmitterID_y,SubmitterName_y,AttachmentsPresent_y,AttachmentsExpected_y,Status_y,ReviewState_y,DeviceID_y,Edits_y,FormVersion_y
0,DEM2-SR-0042,1,1,SEN SOPHOASH,2.0,TEK CHHEAVKOSAL,Dr.NANG SREYNET,DEM2-SR-0042,2026-06-16,08:09:00.000+07:00,...,uuid:3ee39fc1-43c6-4034-ac7e-4656dc96ece8,167.0,T12,0.0,0.0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0.0,v5
1,DEM2-SR-0042,1,1,SEN SOPHOASH,2.0,TEK CHHEAVKOSAL,Dr.NANG SREYNET,DEM2-SR-0042,2026-06-16,08:09:00.000+07:00,...,uuid:3ee39fc1-43c6-4034-ac7e-4656dc96ece8,167.0,T12,0.0,0.0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0.0,v5
2,DEM2-SR-0041,1,1,CHHIT SAMOUN,2.0,Dr.SEM RAVY,Dr.NANG SREYNET,DEM2-SR-0041,2026-06-16,08:04:00.000+07:00,...,uuid:655736aa-fbc2-4731-ae3e-5f68f20b0533,159.0,T04,0.0,0.0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0.0,v5
3,DEM2-SR-0040,1,1,TY SOTHEA,2.0,Dr.NGY MENGHONG,Dr.NANG SREYNET,DEM2-SR-0040,2026-06-16,08:01:00.000+07:00,...,uuid:dbebc07f-ead9-4bf8-ba5e-372625adb029,159.0,T04,0.0,0.0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0.0,v5
4,DEM2-SR-0039,1,1,CHHIT SAMOUN,2.0,Dr.SEM RAVY,Dr.NANG SREYNET,DEM2-SR-0039,2026-06-16,07:48:00.000+07:00,...,uuid:905e0989-5bb3-43d9-bd17-596084c44235,159.0,T04,0.0,0.0,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0.0,v5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,DEM2-PP-0009,1,1,Mai sreyneth,2.0,Dr Nuon Neathvibol,Dr Meng Lun,DEM2-PP-0009,2025-12-27,23:00:00.000+07:00,...,uuid:6a06a770-5ea7-4036-8786-4cb33d8c8b28,156.0,T01,0.0,0.0,NaN,NaN,collect:jcItTlkxdPzoHjMY,0.0,v5
538,NaN,1,1,DAVANN,2.0,Dr CHAN MARDY,Dr Meng Lun,DEM2-PP-0002,2025-12-09,11:20:00.000+07:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,NaN,1,1,DAVANN,2.0,Dr CHAN MARDY,Dr Meng Lun,DEM2-PP-0002,2025-12-09,11:20:00.000+07:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,NaN,1,1,V,2.0,Dr Meng Lun,Dr Meng Lun,DEM1-PP-0001,2025-12-23,10:43:00.000+07:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,NaN,1,1,V,2.0,Dr Meng Lun,Dr Meng Lun,DEM1-PP-0001,2025-12-23,10:43:00.000+07:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [166]:
merged_df = pd.merge(merged_df, c5_df, on="A1", how="left")
merged_df

,A1,A6/1_x,A6/2_x,A8_x,A9_x,A10_x,A11_x,A1_id_x,A1_1_x,A1_2_x,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,DEM2-SR-0042,1,1,SEN SOPHOASH,2.0,TEK CHHEAVKOSAL,Dr.NANG SREYNET,DEM2-SR-0042,2026-06-16,08:09:00.000+07:00,...,uuid:8da9a253-9eac-4647-92e4-c2531037f925,173.0,T18,0.0,0.0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0.0,v7
1,DEM2-SR-0042,1,1,SEN SOPHOASH,2.0,TEK CHHEAVKOSAL,Dr.NANG SREYNET,DEM2-SR-0042,2026-06-16,08:09:00.000+07:00,...,uuid:8da9a253-9eac-4647-92e4-c2531037f925,173.0,T18,0.0,0.0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0.0,v7
2,DEM2-SR-0041,1,1,CHHIT SAMOUN,2.0,Dr.SEM RAVY,Dr.NANG SREYNET,DEM2-SR-0041,2026-06-16,08:04:00.000+07:00,...,uuid:d9f0f707-301e-4733-a5a2-630a423617d7,173.0,T18,0.0,0.0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0.0,v7
3,DEM2-SR-0040,1,1,TY SOTHEA,2.0,Dr.NGY MENGHONG,Dr.NANG SREYNET,DEM2-SR-0040,2026-06-16,08:01:00.000+07:00,...,uuid:fd31bb90-65a8-4e58-a9dd-43eb13165aa9,173.0,T18,0.0,0.0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0.0,v7
4,DEM2-SR-0039,1,1,CHHIT SAMOUN,2.0,Dr.SEM RAVY,Dr.NANG SREYNET,DEM2-SR-0039,2026-06-16,07:48:00.000+07:00,...,uuid:9f22d3b8-3c20-48d9-976a-72e72a6e44c8,173.0,T18,0.0,0.0,NaN,NaN,collect:jHl2uzO0Hmb0l1o5,0.0,v7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,NaN,1,1,V,2.0,Dr Meng Lun,Dr Meng Lun,DEM1-PP-0001,2025-12-23,10:43:00.000+07:00,...,uuid:377923fc-6a43-488f-aeb1-a1027d507bcc,171.0,T16,0.0,0.0,NaN,NaN,collect:1OmvGirXCAZAfOcI,0.0,v5
630,NaN,1,1,V,2.0,Dr Meng Lun,Dr Meng Lun,DEM1-PP-0001,2025-12-23,10:43:00.000+07:00,...,uuid:660c1adf-52d0-4a40-8d7a-54cb94e9ed8c,171.0,T16,0.0,0.0,NaN,NaN,collect:1OmvGirXCAZAfOcI,0.0,v5
631,NaN,1,1,V,2.0,Dr Meng Lun,Dr Meng Lun,DEM1-PP-0001,2025-12-23,10:43:00.000+07:00,...,uuid:a51f90f2-645c-48bc-a6ca-1472c3db5329,171.0,T16,0.0,0.0,NaN,NaN,collect:1OmvGirXCAZAfOcI,0.0,v5
632,NaN,1,1,V,2.0,Dr Meng Lun,Dr Meng Lun,DEM1-PP-0001,2025-12-23,10:43:00.000+07:00,...,uuid:55abd51f-c24f-49dd-a44a-c08219b58208,171.0,T16,0.0,0.0,NaN,NaN,collect:1OmvGirXCAZAfOcI,0.0,v5
633,NaN,1,1,V,2.0,Dr Meng Lun,Dr Meng Lun,DEM1-PP-0001,2025-12-23,10:43:00.000+07:00,...,uuid:4a352e32-cde1-46a5-a101-1da0fed4baed,170.0,T15,0.0,0.0,NaN,NaN,collect:wvNQjIeyEj3rls50,0.0,v5