In [1]:
import pandas as pd
import numpy as np
# import tqdm as notebook_tqdm
# from ydata_profiling import ProfileReport

# A1

In [2]:
file_name = '.././dataset/A1_Questionnaire_Cohort1_Baseline.csv'
a1_df = pd.read_csv(file_name)
a1_df['SubmissionDate'] = pd.to_datetime(a1_df['SubmissionDate']).dt.tz_localize(None)
a1_df.sort_values(by='SubmissionDate', ascending=False, inplace=True)
a1_df.head()

/var/folders/dt/90w7dnxx5xzfd7px48yrrpt00000gn/T/ipykernel_13670/3747523220.py:2: DtypeWarning: Columns (46,53,61,105,150,174,213,216,221,241,243,245,259,308,309,311,325,329,334,386,437,439,440,442,460,462,463,465,466,468,469,471,472,474,512,513,530,549,551,575) have mixed types. Specify dtype option on import or set low_memory=False.
  a1_df = pd.read_csv(file_name)

,SubmissionDate,I1d,I2s,I3e,I4d,I5u,A1,A1manual,A1m_s,A1m_cal,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,2026-03-26 03:06:13.278,2026-03-26,2026-03-26T10:05:17.696+07:00,2026-03-26T10:06:12.754+07:00,collect:RQ1eyOTTgb72DTff,T12,DEM1-SR-0163,NaN,NaN,NaN,...,uuid:0ab7bd80-483e-4c38-821e-6ea46e64ff2e,167,T12,0,0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0,v20
1,2026-03-26 02:43:43.554,2026-03-26,2026-03-26T09:35:15.591+07:00,2026-03-26T09:43:42.850+07:00,collect:HWmr5IpdBFgGHeiN,T03,DEM1-SR-0162,NaN,NaN,NaN,...,uuid:879da10b-dedf-4b18-8999-1e3f1078c537,158,T03,0,0,NaN,NaN,collect:HWmr5IpdBFgGHeiN,0,v20
2,2026-03-26 02:35:02.312,2026-03-26,2026-03-26T09:34:06.394+07:00,2026-03-26T09:35:01.880+07:00,collect:RQ1eyOTTgb72DTff,T12,DEM1-SR-0162,NaN,NaN,NaN,...,uuid:408dc8a3-1319-4518-932d-0ccfa980cb5a,167,T12,0,0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0,v20
3,2026-03-26 02:27:29.347,2026-03-26,2026-03-26T09:18:15.787+07:00,2026-03-26T09:27:28.770+07:00,collect:HWmr5IpdBFgGHeiN,T03,DEM1-SR-0160,NaN,NaN,NaN,...,uuid:98f10b01-2c90-4996-848f-8d2c1ebec01a,158,T03,0,0,NaN,NaN,collect:HWmr5IpdBFgGHeiN,0,v20
4,2026-03-26 02:17:11.293,2026-03-26,2026-03-26T09:15:38.441+07:00,2026-03-26T09:17:10.648+07:00,collect:RQ1eyOTTgb72DTff,T12,DEM1-SR-0159,NaN,NaN,NaN,...,uuid:036becc5-944b-4496-91ef-9248ee40abb0,167,T12,0,0,NaN,NaN,collect:RQ1eyOTTgb72DTff,0,v20

In [3]:
a1_df.shape

(1175, 614)

In [4]:
# a1_df.info()

## Mapping Column Names - follow name in the form

In [5]:
a4_section_mapping = {
    'A1'    : 'ID',
    'A1manual' : 'ID Manual',
    'A4/1'  : 'B. Inclusion Criteria - A4/1',
    'A4/2'  : 'C. Demographic Information - A4/2',
    'A4/3'  : 'D. Animal Contact - A4/3',
    'A4/4'  : 'E. Mosquito Activity Information - A4/4',
    'A4/5'  : 'F. General Knowledge - A4/5',
    'A4/6'  : 'G. Child Information - A4/6',
    'A4/7'  : 'H. Chile Vaccination Record - A4/7',
    'A4/8'  : 'I. Child Medical History - A4/8',
    'A4/9'  : 'J. Physical Examination and Neurological Assessment - A4/9',
    'ID'    : 'A1'
}

In [6]:
A_section = ['SubmissionDate', 'A1', 'A1manual', 'A4/1', 'A4/2', 'A4/3', 'A4/4', 'A4/5', 'A4/6', 'A4/7', 'A4/8', 'A4/9']
a1_df[A_section].rename(columns=a4_section_mapping).head()

,SubmissionDate,ID,ID Manual,B. Inclusion Criteria - A4/1,C. Demographic Information - A4/2,D. Animal Contact - A4/3,E. Mosquito Activity Information - A4/4,F. General Knowledge - A4/5,G. Child Information - A4/6,H. Chile Vaccination Record - A4/7,I. Child Medical History - A4/8,J. Physical Examination and Neurological Assessment - A4/9
0,2026-03-26 03:06:13.278,DEM1-SR-0163,NaN,0,0,0,0,0,0,0,0,1
1,2026-03-26 02:43:43.554,DEM1-SR-0162,NaN,1,1,1,1,1,1,1,1,0
2,2026-03-26 02:35:02.312,DEM1-SR-0162,NaN,0,0,0,0,0,0,0,0,1
3,2026-03-26 02:27:29.347,DEM1-SR-0160,NaN,1,1,1,1,1,1,1,1,0
4,2026-03-26 02:17:11.293,DEM1-SR-0159,NaN,0,0,0,0,0,0,0,0,1

In [7]:
a1_df = a1_df[A_section]

## Fill ID from A1manual to A1

In [8]:
a1_df[a1_df['A1'].isnull()][['A1', 'A1manual']]

a1_df['A1'] = a1_df['A1'].fillna(a1_df['A1manual'])

# a1_df

In [9]:
a1_df[a1_df['A1'].isnull()][['A1', 'A1manual']]

Empty DataFrame
Columns: [A1, A1manual]
Index: []

In [10]:
a1_df[A_section].rename(columns=a4_section_mapping).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 12 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   SubmissionDate                                              1175 non-null   datetime64[ns]
 1   ID                                                          1175 non-null   object
 2   ID Manual                                                   7 non-null      object
 3   B. Inclusion Criteria - A4/1                                1175 non-null   int64
 4   C. Demographic Information - A4/2                           1175 non-null   int64
 5   D. Animal Contact - A4/3                                    1175 non-null   int64
 6   E. Mosquito Activity Information - A4/4                     1175 non-null   int64
 7   F. General Knowledge - A4/5                                 1175 non-null   int64
 8   G. Child Information - A4/6                                 1175 non-null   int64
 9   H. Chile Vaccination Record - A4/7                          1175 non-null   int64
 10  I. Child Medical History - A4/8                             1175 non-null   int64
 11  J. Physical Examination and Neurological Assessment - A4/9  1175 non-null   int64
dtypes: datetime64[ns](1), int64(9), object(2)
memory usage: 110.3+ KB

In [11]:
a1_df['A1'].value_counts()

A1
DEM1-PP-0041    5
DEM1-PP-0090    5
DEM1-PP-0049    5
DEM1-PP-0034    4
DEM1-PP-0004    4
               ..
DEM1-PP-0378    1
DEM1-PP-0360    1
DEM1-PP-0359    1
DEM2-PP-0047    1
DEM1-SR-0163    1
Name: count, Length: 555, dtype: int64

In [12]:
a1_df['A4/1'].value_counts()

for col in a1_df.columns:
    if col.startswith('A4/'):
        print(a1_df[col].value_counts())
        print()

A4/1
0    629
1    546
Name: count, dtype: int64

A4/2
0    629
1    546
Name: count, dtype: int64

A4/3
0    629
1    546
Name: count, dtype: int64

A4/4
0    629
1    546
Name: count, dtype: int64

A4/5
0    629
1    546
Name: count, dtype: int64

A4/6
0    629
1    546
Name: count, dtype: int64

A4/7
0    628
1    547
Name: count, dtype: int64

A4/8
0    629
1    546
Name: count, dtype: int64

A4/9
0    615
1    560
Name: count, dtype: int64

In [13]:
a1_df['A1'].value_counts()

A1
DEM1-PP-0041    5
DEM1-PP-0090    5
DEM1-PP-0049    5
DEM1-PP-0034    4
DEM1-PP-0004    4
               ..
DEM1-PP-0378    1
DEM1-PP-0360    1
DEM1-PP-0359    1
DEM2-PP-0047    1
DEM1-SR-0163    1
Name: count, Length: 555, dtype: int64

In [14]:
a1_df

,SubmissionDate,A1,A1manual,A4/1,A4/2,A4/3,A4/4,A4/5,A4/6,A4/7,A4/8,A4/9
0,2026-03-26 03:06:13.278,DEM1-SR-0163,NaN,0,0,0,0,0,0,0,0,1
1,2026-03-26 02:43:43.554,DEM1-SR-0162,NaN,1,1,1,1,1,1,1,1,0
2,2026-03-26 02:35:02.312,DEM1-SR-0162,NaN,0,0,0,0,0,0,0,0,1
3,2026-03-26 02:27:29.347,DEM1-SR-0160,NaN,1,1,1,1,1,1,1,1,0
4,2026-03-26 02:17:11.293,DEM1-SR-0159,NaN,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1170,2025-11-21 07:04:55.464,DEM1-PP-0002,NaN,0,0,0,0,0,0,0,0,1
1171,2025-11-21 01:02:45.038,DEM1-PP-0001,DEM1-PP-0001,0,0,0,0,0,0,1,0,0
1172,2025-11-20 08:52:53.362,DEM1-PP-0034,DEM1-PP-0034,1,1,1,1,1,1,1,1,0
1173,2025-11-20 03:49:18.801,DEM1-PP-0001,NaN,1,1,1,1,1,1,0,1,0
1174,2025-11-20 02:29:08.402,DEM1-PP-0001,NaN,0,0,0,0,0,0,0,0,1

In [15]:
# a1_df[a1_df['A4/9'] == 1]

In [16]:
# a1_df[a1_df['A4/9'] == 0]

In [17]:
a1_df[a1_df.groupby('A1')['A1'].transform('count') > 1]

,SubmissionDate,A1,A1manual,A4/1,A4/2,A4/3,A4/4,A4/5,A4/6,A4/7,A4/8,A4/9
1,2026-03-26 02:43:43.554,DEM1-SR-0162,NaN,1,1,1,1,1,1,1,1,0
2,2026-03-26 02:35:02.312,DEM1-SR-0162,NaN,0,0,0,0,0,0,0,0,1
3,2026-03-26 02:27:29.347,DEM1-SR-0160,NaN,1,1,1,1,1,1,1,1,0
4,2026-03-26 02:17:11.293,DEM1-SR-0159,NaN,0,0,0,0,0,0,0,0,1
5,2026-03-26 02:15:32.859,DEM1-SR-0160,NaN,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1170,2025-11-21 07:04:55.464,DEM1-PP-0002,NaN,0,0,0,0,0,0,0,0,1
1171,2025-11-21 01:02:45.038,DEM1-PP-0001,DEM1-PP-0001,0,0,0,0,0,0,1,0,0
1172,2025-11-20 08:52:53.362,DEM1-PP-0034,DEM1-PP-0034,1,1,1,1,1,1,1,1,0
1173,2025-11-20 03:49:18.801,DEM1-PP-0001,NaN,1,1,1,1,1,1,0,1,0
1174,2025-11-20 02:29:08.402,DEM1-PP-0001,NaN,0,0,0,0,0,0,0,0,1

# D1

In [18]:
d1_df = pd.read_csv('.././dataset/D1_Screening_Form_Cohort1_Baseline.csv')
d1_df.head()

,SubmissionDate,I1d,I2s,I3e,I4d,I5u,A1,A1manual,A1m_s,A1m_cal,...,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits,FormVersion
0,2026-03-26T01:50:30.167Z,2026-03-26,2026-03-26T08:49:48.984+07:00,2026-03-26T08:50:25.540+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM1-SR-0150,NaN,NaN,NaN,...,uuid:f6781f8c-c614-464c-b1c3-dc576a94d234,159,T04,1,1,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v13
1,2026-03-26T01:49:48.780Z,2026-03-26,2026-03-26T08:49:02.644+07:00,2026-03-26T08:49:42.859+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM1-SR-0151,NaN,NaN,NaN,...,uuid:5c8f4761-f94b-47ac-aa69-a1941ecffad8,159,T04,1,1,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v13
2,2026-03-26T01:49:06.895Z,2026-03-26,2026-03-26T08:48:16.682+07:00,2026-03-26T08:48:57.872+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM1-SR-0152,NaN,NaN,NaN,...,uuid:c328fe65-da4d-472c-9433-d2c534940484,159,T04,1,1,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v13
3,2026-03-26T01:48:06.648Z,2026-03-26,2026-03-26T08:47:09.830+07:00,2026-03-26T08:48:01.123+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM1-SR-0153,NaN,NaN,NaN,...,uuid:3b403f39-01c2-4e13-a5e4-44d6f7b40dc1,159,T04,1,1,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v13
4,2026-03-26T01:46:15.978Z,2026-03-26,2026-03-26T08:44:59.112+07:00,2026-03-26T08:46:09.772+07:00,collect:pe9NIh45rSyFr4qJ,T04,DEM1-SR-0154,NaN,NaN,NaN,...,uuid:664c8445-fc56-4ac2-9164-a2d900e90191,159,T04,1,1,NaN,NaN,collect:pe9NIh45rSyFr4qJ,0,v13

In [19]:
d1_df['A1'] = d1_df['A1'].fillna(d1_df['A1manual'])

In [20]:
useful_column = ['SubmissionDate','A1', 'A1manual', 'SubmitterID', 'SubmitterName', 'Edits']
d1_df = d1_df[useful_column]

In [21]:
d1_df

,SubmissionDate,A1,A1manual,SubmitterID,SubmitterName,Edits
0,2026-03-26T01:50:30.167Z,DEM1-SR-0150,NaN,159,T04,0
1,2026-03-26T01:49:48.780Z,DEM1-SR-0151,NaN,159,T04,0
2,2026-03-26T01:49:06.895Z,DEM1-SR-0152,NaN,159,T04,0
3,2026-03-26T01:48:06.648Z,DEM1-SR-0153,NaN,159,T04,0
4,2026-03-26T01:46:15.978Z,DEM1-SR-0154,NaN,159,T04,0
...,...,...,...,...,...,...
543,2025-11-24T03:34:16.729Z,DEM1-PP-9001,DEM1-PP-9001,159,T04,0
544,2025-11-21T10:25:43.146Z,DEM1-PP-0004,NaN,157,T02,0
545,2025-11-21T09:48:55.576Z,DEM1-PP-0003,DEM1-PP-0003,158,T03,0
546,2025-11-21T09:46:33.598Z,DEM1-PP-0002,DEM1-PP-0002,158,T03,0
547,2025-11-21T01:16:07.042Z,DEM1-PP-0001,NaN,157,T02,0

In [22]:
d1_df.columns
print(d1_df['A1'].nunique())
d1_df['A1'].unique()

545

array(['DEM1-SR-0150', 'DEM1-SR-0151', 'DEM1-SR-0152', 'DEM1-SR-0153',
       'DEM1-SR-0154', 'DEM1-SR-0155', 'DEM1-SR-0156', 'DEM1-SR-0157',
       'DEM1-SR-0158', 'DEM1-PP-0392', 'DEM1-PP-0391', 'DEM1-PP-0390',
       'DEM1-SR-0148', 'DEM1-PP-0383', 'DEM1-SR-0149', 'DEM1-SR-0147',
       'DEM1-PP-0389', 'DEM1-PP-0388', 'DEM1-PP-0387', 'DEM1-PP-0386',
       'DEM1-PP-0385', 'DEM1-PP-0384', 'DEM1-SR-0146', 'DEM1-SR-0145',
       'DEM1-SR-0144', 'DEM1-SR-0142', 'DEM1-SR-0143', 'DEM1-SR-0141',
       'DEM1-PP-0382', 'DEM1-PP-0381', 'DEM1-PP-0380', 'DEM1-PP-0379',
       'DEM1-PP-0378', 'DEM1-SR-0139', 'DEM1-SR-0138', 'DEM1-SR-0137',
       'DEM1-SR-0140', 'DEM1-SR-0136', 'DEM1-PP-0377', 'DEM1-SR-0135',
       'DEM1-SR-0134', 'DEM1-SR-0133', 'DEM1-SR-0132', 'DEM1-SR-0131',
       'DEM1-SR-0128', 'DEM1-SR-0127', 'DEM1-SR-0130', 'DEM1-SR-0129',
       'DEM1-PP-0376', 'DEM1-PP-0375', 'DEM1-SR-0126', 'DEM1-SR-0124',
       'DEM1-SR-0125', 'DEM1-SR-0117', 'DEM1-SR-0116', 'DEM1-SR-0121',
       'DEM1-SR-0122', 'DEM1-SR-0123', 'DEM1-SR-0120', 'DEM1-SR-0119',
       'DEM1-SR-0118', 'DEM1-PP-0374', 'DEM1-PP-0373', 'DEM1-PP-0372',
       'DEM1-PP-0371', 'DEM1-SR-0115', 'DEM1-SR-0114', 'DEM1-PP-0369',
       'DEM1-PP-0368', 'DEM1-PP-0367', 'DEM1-SR-0110', 'DEM1-PP-0370',
       'DEM1-PP-0366', 'DEM1-PP-0365', 'DEM1-SR-0109', 'DEM1-SR-0108',
       'DEM1-SR-0107', 'DEM1-PP-0364', 'DEM1-PP-0363', 'DEM1-PP-0362',
       'DEM1-SR-0105', 'DEM1-SR-0104', 'DEM1-SR-0103', 'DEM1-SR-0102',
       'DEM1-SR-0101', 'DEM1-SR-0100', 'DEM1-SR-0099', 'DEM1-SR-0098',
       'DEM1-SR-0097', 'DEM1-SR-0096', 'DEM1-SR-0095', 'DEM1-SR-0094',
       'DEM1-PP-0361', 'DEM1-SR-0092', 'DEM1-SR-0090', 'DEM1-SR-0091',
       'DEM1-SR-0089', 'DEM1-PP-0360', 'DEM1-PP-0359', 'DEM1-SR-0086',
       'DEM1-SR-0082', 'DEM1-SR-0079', 'DEM1-SR-0078', 'DEM1-SR-0088',
       'DEM1-SR-0087', 'DEM1-PP-0358', 'DEM1-SR-0085', 'DEM1-SR-0084',
       'DEM1-SR-0083', 'DEM1-SR-0081', 'DEM1-SR-0080', 'DEM1-SR-0077',
       'DEM1-SR-0076', 'DEM1-SR-0075', 'DEM1-SR-0074', 'DEM1-PP-0357',
       'DEM1-PP-0356', 'DEM1-SR-0073', 'DEM1-SR-0071', 'DEM1-PP-0355',
       'DEM1-SR-0066', 'DEM1-SR-0067', 'DEM1-SR-0070', 'DEM1-SR-0069',
       'DEM1-SR-0068', 'DEM1-PP-0354', 'DEM1-SR-0065', 'DEM1-SR-0064',
       'DEM1-PP-0353', 'DEM1-SR-0063', 'DEM1-SR-0062', 'DEM1-PP-0352',
       'DEM1-PP-0351', 'DEM1-SR-0060', 'DEM1-SR-0059', 'DEM1-SR-0054',
       'DEM1-SR-0061', 'DEM1-PP-0350', 'DEM1-PP-0349', 'DEM1-SR-0058',
       'DEM1-SR-0057', 'DEM1-SR-0056', 'DEM1-SR-0055', 'DEM1-SR-0053',
       'DEM1-SR-0052', 'DEM1-PP-0348', 'DEM1-SR-0051', 'DEM1-SR-0050',
       'DEM1-SR-0049', 'DEM1-PP-0347', 'DEM1-PP-0346', 'DEM1-PP-0345',
       'DEM1-SR-0047', 'DEM1-SR-0046', 'DEM1-SR-0048', 'DEM1-SR-0045',
       'DEM1-SR-0043', 'DEM1-SR-0042', 'DEM1-SR-0040', 'DEM1-SR-0039',
       'DEM1-SR-0037', 'DEM1-PP-0344', 'DEM1-PP-0343', 'DEM1-PP-0342',
       'DEM1-SR-0038', 'DEM1-SR-0041', 'DEM1-SR-0044', 'DEM1-SR-0036',
       'DEM1-SR-0035', 'DEM1-SR-0034', 'DEM1-SR-0033', 'DEM1-SR-0032',
       'DEM1-SR-0031', 'DEM1-SR-0030', 'DEM1-SR-0028', 'DEM1-SR-0026',
       'DEM1-SR-0025', 'DEM1-SR-0023', 'DEM1-SR-0024', 'DEM1-SR-0022',
       'DEM1-SR-0021', 'DEM1-SR-0020', 'DEM1-SR-0018', 'DEM1-SR-0017',
       'DEM1-SR-0016', 'DEM1-SR-0014', 'DEM1-SR-0013', 'DEM1-SR-0010',
       'DEM1-SR-0015', 'DEM1-SR-0009', 'DEM1-SR-0008', 'DEM1-SR-0007',
       'DEM1-SR-0004', 'DEM1-SR-0003', 'DEM1-SR-0006', 'DEM1-SR-0005',
       'DEM1-PP-0341', 'DEM1-PP-0340', 'DEM1-PP-0339', 'DEM1-PP-0338',
       'DEM1-PP-0337', 'DEM1-PP-0335', 'DEM1-PP-0336', 'DEM1-PP-0334',
       'DEM1-PP-0333', 'DEM1-PP-0332', 'DEM1-PP-0331', 'DEM1-PP-0330',
       'DEM1-PP-0329', 'DEM1-SR-0027', 'DEM1-SR-0029', 'DEM1-PP-0328',
       'DEM1-PP-0327', 'DEM1-SR-0019', 'DEM2-SR-0002', 'DEM1-PP-0326',
       'DEM1-PP-0325', 'DEM1-PP-0324', 'DEM1-PP-0323', 'DEM1-PP-0322',
       'DEM1-PP-0321', 'DEM1-SR-0012', 'DEM1-SR-0011', 'DEM1-SR-0002',
       'DEM1-SR-0001', 'DEM1-PP-0320', 'DEM1-PP-0319', 'DEM1-PP-0318',
       'DEM1-PP-0317', 'DEM1-PP-0316', 'DEM1-PP-0315', 'DEM1-PP-0314',
       'DEM1-PP-0313', 'DEM1-PP-0312', 'DEM1-PP-0311', 'DEM1-PP-0310',
       'DEM1-PP-0309', 'DEM1-PP-0308', 'DEM1-PP-0307', 'DEM1-PP-0306',
       'DEM1-PP-0304', 'DEM1-PP-0303', 'DEM1-PP-0305', 'DEM1-PP-0302',
       'DEM1-PP-0301', 'DEM1-PP-0300', 'DEM1-PP-0299', 'DEM1-PP-0298',
       'DEM1-PP-0297', 'DEM1-PP-0295', 'DEM1-PP-0294', 'DEM1-PP-0296',
       'DEM1-PP-0293', 'DEM1-PP-0290', 'DEM1-PP-0288', 'DEM1-PP-0291',
       'DEM1-PP-0289', 'DEM1-PP-0287', 'DEM1-PP-0286', 'DEM1-PP-0285',
       'DEM1-PP-0284', 'DEM1-PP-0283', 'DEM1-PP-0282', 'DEM1-PP-0281',
       'DEM1-PP-0280', 'DEM1-PP-0279', 'DEM1-PP-0278', 'DEM1-PP-0277',
       'DEM1-PP-0276', 'DEM1-PP-0274', 'DEM1-PP-0273', 'DEM1-PP-0271',
       'DEM1-PP-0272', 'DEM1-PP-0275', 'DEM1-PP-0270', 'DEM1-PP-0268',
       'DEM1-PP-0269', 'DEM1-PP-0266', 'DEM1-PP-0267', 'DEM1-PP-0265',
       'DEM1-PP-0264', 'DEM1-PP-0263', 'DEM1-PP-0262', 'DEM1-PP-0261',
       'DEM1-PP-0259', 'DEM1-PP-0260', 'DEM1-PP-0257', 'DEM1-PP-0256',
       'DEM1-PP-0254', 'DEM1-PP-0255', 'DEM1-PP-0253', 'DEM1-PP-0258',
       'DEM1-PP-0252', 'DEM1-PP-0251', 'DEM1-PP-0250', 'DEM1-PP-0249',
       'DEM1-PP-0247', 'DEM1-PP-0248', 'DEM1-PP-0246', 'DEM1-PP-0245',
       'DEM1-PP-0244', 'DEM1-PP-0243', 'DEM1-PP-0241', 'DEM1-PP-0242',
       'DEM1-PP-0240', 'DEM1-PP-0238', 'DEM1-PP-0239', 'DEM1-PP-0237',
       'DEM1-PP-9002', 'DEM1-PP-0236', 'DEM1-PP-0234', 'DEM1-PP-0233',
       'DEM1-PP-0228', 'DEM1-PP-0231', 'DEM1-PP-0232', 'DEM1-PP-0235',
       'DEM1-PP-0230', 'DEM1-PP-0229', 'DEM1-PP-0227', 'DEM1-PP-0226',
       'DEM1-PP-0225', 'DEM1-PP-0223', 'DEM1-PP-0222', 'DEM1-PP-0220',
       'DEM1-PP-0224', 'DEM1-PP-0221', 'DEM1-PP-0219', 'DEM1-PP-0217',
       'DEM1-PP-0218', 'DEM1-PP-0216', 'DEM1-PP-0215', 'DEM1-PP-0213',
       'DEM1-PP-0214', 'DEM1-PP-0210', 'DEM1-PP-0212', 'DEM1-PP-0211',
       'DEM1-PP-0206', 'DEM1-PP-0209', 'DEM1-PP-0207', 'DEM1-PP-0208',
       'DEM1-PP-0204', 'DEM1-PP-0202', 'DEM1-PP-0203', 'DEM1-PP-0201',
       'DEM1-PP-0200', 'DEM1-PP-0197', 'DEM1-PP-0196', 'DEM1-PP-0193',
       'DEM1-PP-0191', 'DEM1-PP-0199', 'DEM1-PP-0198', 'DEM1-PP-0195',
       'DEM1-PP-0194', 'DEM1-PP-0192', 'DEM1-PP-0190', 'DEM1-PP-0188',
       'DEM1-PP-0186', 'DEM1-PP-0185', 'DEM1-PP-0184', 'DEM1-PP-0182',
       'DEM1-PP-0189', 'DEM1-PP-0187', 'DEM1-PP-0183', 'DEM1-PP-0181',
       'DEM1-PP-0180', 'DEM1-PP-0179', 'DEM1-PP-0178', 'DEM1-PP-0177',
       'DEM1-PP-0176', 'DEM1-PP-0175', 'DEM1-PP-0174', 'DEM1-PP-0173',
       'DEM1-PP-0172', 'DEM1-PP-0171', 'DEM1-PP-0170', 'DEM1-PP-0169',
       'DEM1-PP-0168', 'DEM1-PP-0165', 'DEM1-PP-0164', 'DEM1-PP-0167',
       'DEM1-PP-0163', 'DEM1-PP-0166', 'DEM1-PP-0161', 'DEM1-PP-0162',
       'DEM1-PP-0160', 'DEM1-PP-0159', 'DEM1-PP-0158', 'DEM1-PP-0156',
       'DEM1-PP-0157', 'DEM1-PP-0155', 'DEM1-PP-0154', 'DEM1-PP-0153',
       'DEM1-PP-0151', 'DEM1-PP-0148', 'DEM1-PP-0152', 'DEM1-PP-0150',
       'DEM1-PP-0149', 'DEM1-PP-0147', 'DEM1-PP-0143', 'DEM1-PP-0142',
       'DEM1-PP-0137', 'DEM1-PP-0146', 'DEM1-PP-0145', 'DEM1-PP-0144',
       'DEM1-PP-0141', 'DEM1-PP-0140', 'DEM1-PP-0138', 'DEM1-PP-0135',
       'DEM1-PP-0139', 'DEM1-PP-0136', 'DEM1-PP-0134', 'DEM1-PP-0133',
       'DEM1-PP-0132', 'DEM1-PP-0131', 'DEM1-PP-0130', 'DEM1-PP-0129',
       'DEM1-PP-0124', 'DEM1-PP-0123', 'DEM1-PP-0122', 'DEM1-PP-0120',
       'DEM1-PP-0118', 'DEM1-PP-0128', 'DEM1-PP-0127', 'DEM1-PP-0125',
       'DEM1-PP-0126', 'DEM1-PP-0121', 'DEM1-PP-0119', 'DEM1-PP-0117',
       'DEM1-PP-0115', 'DEM1-PP-0116', 'DEM1-PP-0114', 'DEM1-PP-0113',
       'DEM1-PP-0111', 'DEM1-PP-0109', 'DEM1-PP-0107', 'DEM1-PP-0112',
       'DEM1-PP-0110', 'DEM1-PP-0108', 'DEM1-PP-0106', 'DEM1-PP-0104',
       'DEM1-PP-0102', 'DEM1-PP-0100', 'DEM1-PP-0098', 'DEM1-PP-0105',
       'DEM1-PP-0103', 'DEM1-PP-0101', 'DEM1-PP-0099', 'DEM1-PP-0096',
       'DEM1-PP-0097', 'DEM1-PP-0095', 'DEM1-PP-0094', 'DEM1-PP-0093',
       'DEM1-PP-0092', 'DEM1-PP-0090', 'DEM1-PP-0091', 'DEM1-PP-0089',
       'DEM1-PP-0088', 'DEM1-PP-0087', 'DEM1-PP-0086', 'DEM1-PP-0085',
       'DEM1-PP-0083', 'DEM1-PP-0082', 'DEM1-PP-0081', 'DEM1-PP-0084',
       'DEM1-PP-0080', 'DEM1-PP-0079', 'DEM1-PP-0078', 'DEM1-PP-0077',
       'DEM1-PP-0076', 'DEM1-PP-0074', 'DEM1-PP-0073', 'DEM1-PP-0072',
       'DEM1-PP-0071', 'DEM1-PP-0075', 'DEM1-PP-0070', 'DEM1-PP-0069',
       'DEM1-PP-0068', 'DEM1-PP-0067', 'DEM1-PP-0066', 'DEM1-PP-0065',
       'DEM1-PP-0064', 'DEM1-PP-0063', 'DEM1-PP-0062', 'DEM1-PP-0061',
       'DEM1-PP-0060', 'DEM1-PP-0059', 'DEM1-PP-0058', 'DEM1-PP-0057',
       'DEM1-PP-0056', 'DEM1-PP-0055', 'DEM1-PP-0054', 'DEM1-PP-0053',
       'DEM1-PP-0052', 'DEM1-PP-0051', 'DEM1-PP-0050', 'DEM1-PP-0049',
       'DEM1-PP-0048', 'DEM1-PP-0046', 'DEM1-PP-0047', 'DEM1-PP-0045',
       'DEM1-PP-0044', 'DEM1-PP-0042', 'DEM1-PP-0043', 'DEM1-PP-0041',
       'DEM1-PP-0040', 'DEM1-PP-0038', 'DEM1-PP-0036', 'DEM1-PP-0039',
       'DEM1-PP-0037', 'DEM1-PP-0035', 'DEM1-PP-0034', 'DEM1-PP-0033',
       'DEM1-PP-0032', 'DEM1-PP-0031', 'DEM1-PP-0030', 'DEM1-PP-0029',
       'DEM1-PP-0028', 'DEM1-PP-0027', 'DEM1-PP-0026', 'DEM1-PP-0025',
       'DEM1-PP-0024', 'DEM1-PP-0023', 'DEM1-PP-0022', 'DEM1-PP-0021',
       'DEM1-PP-0020', 'DEM1-PP-0019', 'DEM1-PP-0017', 'DEM1-PP-0018',
       'DEM1-PP-0016', 'DEM1-PP-0015', 'DEM1-PP-0014', 'DEM1-PP-0013',
       'DEM1-PP-0012', 'DEM1-PP-0011', 'DEM1-PP-0010', 'DEM1-PP-0009',
       'DEM1-PP-0006', 'DEM1-PP-0008', 'DEM1-PP-0007', 'DEM1-PP-0005',
       'DEM1-PP-9001', 'DEM1-PP-0004', 'DEM1-PP-0003', 'DEM1-PP-0002',
       'DEM1-PP-0001'], dtype=object)

In [23]:
d1_df['A1'].value_counts()

A1
DEM1-PP-0219    2
DEM1-PP-0073    2
DEM1-SR-0142    2
DEM1-SR-0150    1
DEM1-PP-0179    1
               ..
DEM1-SR-0025    1
DEM1-SR-0026    1
DEM1-SR-0028    1
DEM1-SR-0030    1
DEM1-PP-0001    1
Name: count, Length: 545, dtype: int64

In [24]:
d1_df[d1_df.groupby('A1')['A1'].transform('count') > 1]

,SubmissionDate,A1,A1manual,SubmitterID,SubmitterName,Edits
25,2026-03-23T10:35:21.453Z,DEM1-SR-0142,NaN,158,T03,0
27,2026-03-23T10:06:31.002Z,DEM1-SR-0142,NaN,158,T03,0
327,2026-01-16T07:33:18.201Z,DEM1-PP-0219,NaN,158,T03,0
328,2026-01-16T02:48:54.883Z,DEM1-PP-0219,NaN,158,T03,0
472,2025-12-12T07:16:11.902Z,DEM1-PP-0073,NaN,157,T02,0
474,2025-12-12T02:31:45.462Z,DEM1-PP-0073,NaN,159,T04,0

In [25]:
d1_df

,SubmissionDate,A1,A1manual,SubmitterID,SubmitterName,Edits
0,2026-03-26T01:50:30.167Z,DEM1-SR-0150,NaN,159,T04,0
1,2026-03-26T01:49:48.780Z,DEM1-SR-0151,NaN,159,T04,0
2,2026-03-26T01:49:06.895Z,DEM1-SR-0152,NaN,159,T04,0
3,2026-03-26T01:48:06.648Z,DEM1-SR-0153,NaN,159,T04,0
4,2026-03-26T01:46:15.978Z,DEM1-SR-0154,NaN,159,T04,0
...,...,...,...,...,...,...
543,2025-11-24T03:34:16.729Z,DEM1-PP-9001,DEM1-PP-9001,159,T04,0
544,2025-11-21T10:25:43.146Z,DEM1-PP-0004,NaN,157,T02,0
545,2025-11-21T09:48:55.576Z,DEM1-PP-0003,DEM1-PP-0003,158,T03,0
546,2025-11-21T09:46:33.598Z,DEM1-PP-0002,DEM1-PP-0002,158,T03,0
547,2025-11-21T01:16:07.042Z,DEM1-PP-0001,NaN,157,T02,0

In [26]:
a1_df

,SubmissionDate,A1,A1manual,A4/1,A4/2,A4/3,A4/4,A4/5,A4/6,A4/7,A4/8,A4/9
0,2026-03-26 03:06:13.278,DEM1-SR-0163,NaN,0,0,0,0,0,0,0,0,1
1,2026-03-26 02:43:43.554,DEM1-SR-0162,NaN,1,1,1,1,1,1,1,1,0
2,2026-03-26 02:35:02.312,DEM1-SR-0162,NaN,0,0,0,0,0,0,0,0,1
3,2026-03-26 02:27:29.347,DEM1-SR-0160,NaN,1,1,1,1,1,1,1,1,0
4,2026-03-26 02:17:11.293,DEM1-SR-0159,NaN,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1170,2025-11-21 07:04:55.464,DEM1-PP-0002,NaN,0,0,0,0,0,0,0,0,1
1171,2025-11-21 01:02:45.038,DEM1-PP-0001,DEM1-PP-0001,0,0,0,0,0,0,1,0,0
1172,2025-11-20 08:52:53.362,DEM1-PP-0034,DEM1-PP-0034,1,1,1,1,1,1,1,1,0
1173,2025-11-20 03:49:18.801,DEM1-PP-0001,NaN,1,1,1,1,1,1,0,1,0
1174,2025-11-20 02:29:08.402,DEM1-PP-0001,NaN,0,0,0,0,0,0,0,0,1

## Calculate the completeness of the survey

In [27]:
result_dict = {}
for id in d1_df['A1']:
    try:
        tmp_df = a1_df[a1_df['A1'] == id]
        # print(tmp_df.shape[0])
        col_list = tmp_df.columns[3:]

        condition_dict = {}

        for col in col_list:
            # print(col,"=" , tmp_df[col].sum())
            condition_dict[col] = int(tmp_df[col].sum())
        condition_dict['Record in A1'] = tmp_df.shape[0]


        if (condition_dict['A4/1'] == 1 and condition_dict['A4/2'] == 1 
            and condition_dict['A4/3'] == 1 and condition_dict['A4/4'] == 1 
            and condition_dict['A4/5'] == 1 and condition_dict['A4/6'] == 1 
            and condition_dict['A4/7'] == 1 and condition_dict['A4/8'] == 1 
            and condition_dict['A4/9'] == 1):
            pass
        else:
            print(tmp_df)
            print(id)
            print(condition_dict)
            print(id, "is not completed! or ERROR")
            print()
            result_dict[id] = condition_dict

    except:
        print('NO ID')
    # break

print(result_dict)

            SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
21 2026-03-25 07:48:54.248  DEM1-SR-0151      NaN     0     0     0     0

    A4/5  A4/6  A4/7  A4/8  A4/9
21     0     0     0     0     1
DEM1-SR-0151
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}
DEM1-SR-0151 is not completed! or ERROR

            SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
17 2026-03-25 09:10:15.664  DEM1-SR-0156      NaN     0     0     0     0

    A4/5  A4/6  A4/7  A4/8  A4/9
17     0     0     0     0     1
DEM1-SR-0156
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}
DEM1-SR-0156 is not completed! or ERROR

Empty DataFrame
Columns: [SubmissionDate, A1, A1manual, A4/1, A4/2, A4/3, A4/4, A4/5, A4/6, A4/7, A4/8, A4/9]
Index: []
DEM1-PP-0392
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}
DEM1-PP-0392 is not completed! or ERROR

Empty DataFrame
Columns: [SubmissionDate, A1, A1manual, A4/1, A4/2, A4/3, A4/4, A4/5, A4/6, A4/7, A4/8, A4/9]
Index: []
DEM1-PP-0391
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}
DEM1-PP-0391 is not completed! or ERROR

            SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
35 2026-03-25 01:23:14.889  DEM1-PP-0383      NaN     1     1     1     1

    A4/5  A4/6  A4/7  A4/8  A4/9
35     1     1     1     1     0
DEM1-PP-0383
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0383 is not completed! or ERROR

            SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
42 2026-03-24 08:21:58.227  DEM1-PP-0389      NaN     1     1     1     1

    A4/5  A4/6  A4/7  A4/8  A4/9
42     1     1     1     1     0
DEM1-PP-0389
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0389 is not completed! or ERROR

            SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
62 2026-03-23 06:55:51.163  DEM1-PP-0382      NaN     1     1     1     1

    A4/5  A4/6  A4/7  A4/8  A4/9
62     1     1     1     1     0
DEM1-PP-0382
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0382 is not completed! or ERROR

Empty DataFrame
Columns: [SubmissionDate, A1, A1manual, A4/1, A4/2, A4/3, A4/4, A4/5, A4/6, A4/7, A4/8, A4/9]
Index: []
DEM1-PP-0381
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}
DEM1-PP-0381 is not completed! or ERROR

            SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
30 2026-03-25 03:54:51.368  DEM1-PP-0380      NaN     0     0     0     0

    A4/5  A4/6  A4/7  A4/8  A4/9
30     0     0     0     0     1
DEM1-PP-0380
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}
DEM1-PP-0380 is not completed! or ERROR

            SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
63 2026-03-23 06:29:26.429  DEM1-PP-0378      NaN     1     1     1     1

    A4/5  A4/6  A4/7  A4/8  A4/9
63     1     1     1     1     0
DEM1-PP-0378
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0378 is not completed! or ERROR

            SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
78 2026-03-20 02:52:22.900  DEM1-PP-0377      NaN     1     1     1     1

    A4/5  A4/6  A4/7  A4/8  A4/9
78     1     1     1     1     0
DEM1-PP-0377
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0377 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
107 2026-03-19 02:06:08.241  DEM1-PP-0372      NaN     0     0     0     0

     A4/5  A4/6  A4/7  A4/8  A4/9
107     0     0     0     0     1
DEM1-PP-0372
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}
DEM1-PP-0372 is not completed! or ERROR

Empty DataFrame
Columns: [SubmissionDate, A1, A1manual, A4/1, A4/2, A4/3, A4/4, A4/5, A4/6, A4/7, A4/8, A4/9]
Index: []
DEM1-PP-0369
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}
DEM1-PP-0369 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
105 2026-03-19 02:14:34.659  DEM1-PP-0368      NaN     0     0     0     0

     A4/5  A4/6  A4/7  A4/8  A4/9
105     0     0     0     0     1
DEM1-PP-0368
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}
DEM1-PP-0368 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
139 2026-03-17 02:45:11.675  DEM1-PP-0367      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
139     1     1     1     1     0
DEM1-PP-0367
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0367 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
159 2026-03-16 02:01:31.062  DEM1-PP-0364      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
159     1     1     1     1     0
DEM1-PP-0364
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0364 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
181 2026-03-13 05:23:05.026  DEM1-SR-0103      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
181     1     1     1     1     0
DEM1-SR-0103
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-SR-0103 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
172 2026-03-13 06:34:35.660  DEM1-SR-0096      NaN     0     0     0     0
185 2026-03-13 02:37:38.886  DEM1-SR-0096      NaN     1     1     1     1
186 2026-03-13 02:06:22.645  DEM1-SR-0096      NaN     0     0     0     0

     A4/5  A4/6  A4/7  A4/8  A4/9
172     0     0     0     0     1
185     1     1     1     1     0
186     0     0     0     0     1
DEM1-SR-0096
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}
DEM1-SR-0096 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
199 2026-03-12 03:55:46.916  DEM1-PP-0360      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
199     1     1     1     1     0
DEM1-PP-0360
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0360 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
200 2026-03-12 03:55:18.500  DEM1-PP-0359      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
200     1     1     1     1     0
DEM1-PP-0359
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0359 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
160 2026-03-13 14:38:49.872  DEM1-PP-0352      NaN     1     1     1     1
251 2026-03-09 07:37:45.783  DEM1-PP-0352      NaN     0     0     0     0
252 2026-03-09 07:36:25.293  DEM1-PP-0352      NaN     0     0     0     0

     A4/5  A4/6  A4/7  A4/8  A4/9
160     1     1     1     1     0
251     0     0     0     0     1
252     0     0     0     0     1
DEM1-PP-0352
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}
DEM1-PP-0352 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
316 2026-03-03 07:22:53.055  DEM1-PP-0345      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
316     1     1     1     1     0
DEM1-PP-0345
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0345 is not completed! or ERROR

Empty DataFrame
Columns: [SubmissionDate, A1, A1manual, A4/1, A4/2, A4/3, A4/4, A4/5, A4/6, A4/7, A4/8, A4/9]
Index: []
DEM2-SR-0002
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}
DEM2-SR-0002 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
485 2026-02-13 02:33:11.512  DEM1-PP-0310      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
485     1     1     1     1     0
DEM1-PP-0310
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0310 is not completed! or ERROR

Empty DataFrame
Columns: [SubmissionDate, A1, A1manual, A4/1, A4/2, A4/3, A4/4, A4/5, A4/6, A4/7, A4/8, A4/9]
Index: []
DEM1-PP-9002
{'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}
DEM1-PP-9002 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
666 2026-01-16 07:57:35.509  DEM1-PP-0220      NaN     0     0     0     0
671 2026-01-16 07:38:46.158  DEM1-PP-0220      NaN     1     1     1     1
675 2026-01-16 02:14:24.787  DEM1-PP-0220      NaN     0     0     0     0

     A4/5  A4/6  A4/7  A4/8  A4/9
666     0     0     0     0     1
671     1     1     1     1     0
675     0     0     0     0     1
DEM1-PP-0220
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}
DEM1-PP-0220 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
667 2026-01-16 07:56:18.110  DEM1-PP-0219      NaN     0     0     0     0
674 2026-01-16 02:45:26.330  DEM1-PP-0219      NaN     1     1     1     1
676 2026-01-16 02:13:17.602  DEM1-PP-0219      NaN     0     0     0     0

     A4/5  A4/6  A4/7  A4/8  A4/9
667     0     0     0     0     1
674     1     1     1     1     0
676     0     0     0     0     1
DEM1-PP-0219
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}
DEM1-PP-0219 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
667 2026-01-16 07:56:18.110  DEM1-PP-0219      NaN     0     0     0     0
674 2026-01-16 02:45:26.330  DEM1-PP-0219      NaN     1     1     1     1
676 2026-01-16 02:13:17.602  DEM1-PP-0219      NaN     0     0     0     0

     A4/5  A4/6  A4/7  A4/8  A4/9
667     0     0     0     0     1
674     1     1     1     1     0
676     0     0     0     0     1
DEM1-PP-0219
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}
DEM1-PP-0219 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
690 2026-01-14 03:15:52.510  DEM1-PP-0212      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
690     1     1     1     1     0
DEM1-PP-0212
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}
DEM1-PP-0212 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
686 2026-01-15 02:35:06.418  DEM1-PP-0206      NaN     0     0     0     0
687 2026-01-15 02:33:14.463  DEM1-PP-0206      NaN     0     0     0     0
696 2026-01-14 01:57:57.201  DEM1-PP-0206      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
686     0     0     0     0     1
687     0     0     0     0     1
696     1     1     1     1     0
DEM1-PP-0206
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}
DEM1-PP-0206 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
729 2026-01-12 05:15:21.577  DEM1-PP-0182      NaN     1     1     1     1
774 2026-01-09 04:00:08.252  DEM1-PP-0182      NaN     0     0     0     0
777 2026-01-09 02:34:56.269  DEM1-PP-0182      NaN     0     0     0     0

     A4/5  A4/6  A4/7  A4/8  A4/9
729     1     1     1     1     0
774     0     0     0     0     1
777     0     0     0     0     1
DEM1-PP-0182
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}
DEM1-PP-0182 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
884 2025-12-26 03:44:40.148  DEM1-PP-0119      NaN     0     0     0     0
888 2025-12-26 02:37:46.320  DEM1-PP-0119      NaN     0     0     0     0
896 2025-12-25 06:59:48.735  DEM1-PP-0119      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
884     0     0     0     0     1
888     0     0     0     0     1
896     1     1     1     1     0
DEM1-PP-0119
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}
DEM1-PP-0119 is not completed! or ERROR

             SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
551 2026-02-02 06:15:22.515  DEM1-PP-0090      NaN     0     0     0     0
731 2026-01-12 04:18:04.508  DEM1-PP-0090      NaN     0     0     0     0
841 2025-12-30 09:34:58.820  DEM1-PP-0090      NaN     0     0     0     0
843 2025-12-30 09:29:56.203  DEM1-PP-0090      NaN     0     0     0     0
956 2025-12-17 07:26:52.053  DEM1-PP-0090      NaN     1     1     1     1

     A4/5  A4/6  A4/7  A4/8  A4/9
551     0     0     1     0     0
731     0     0     0     0     1
841     0     0     0     0     1
843     0     0     0     0     1
956     1     1     0     1     0
DEM1-PP-0090
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 3, 'Record in A1': 5}
DEM1-PP-0090 is not completed! or ERROR

              SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
981  2025-12-15 01:19:48.938  DEM1-PP-0049      NaN     0     0     0     0
1043 2025-12-08 07:23:04.973  DEM1-PP-0049      NaN     0     0     0     0
1044 2025-12-08 07:18:18.544  DEM1-PP-0049      NaN     0     0     0     0
1056 2025-12-05 03:03:42.022  DEM1-PP-0049      NaN     1     1     1     1
1057 2025-12-05 02:55:50.886  DEM1-PP-0049      NaN     0     0     0     0

      A4/5  A4/6  A4/7  A4/8  A4/9
981      0     0     1     0     0
1043     0     0     0     0     1
1044     0     0     0     0     1
1056     1     1     0     1     0
1057     0     0     0     0     1
DEM1-PP-0049
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 3, 'Record in A1': 5}
DEM1-PP-0049 is not completed! or ERROR

              SubmissionDate            A1      A1manual  A4/1  A4/2  A4/3  \
867  2025-12-28 03:12:27.299  DEM1-PP-0045  DEM1-PP-0045     0     0     0
1063 2025-12-04 09:45:37.597  DEM1-PP-0045           NaN     1     1     1

      A4/4  A4/5  A4/6  A4/7  A4/8  A4/9
867      0     0     0     0     0     1
1063     1     1     1     0     1     0
DEM1-PP-0045
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 0, 'A4/8': 1, 'A4/9': 1, 'Record in A1': 2}
DEM1-PP-0045 is not completed! or ERROR

              SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
1066 2025-12-04 04:13:19.094  DEM1-PP-0042      NaN     0     0     0     0
1068 2025-12-04 03:44:56.350  DEM1-PP-0042      NaN     0     0     0     0
1069 2025-12-04 03:43:42.298  DEM1-PP-0042      NaN     0     0     0     0
1072 2025-12-04 03:04:13.629  DEM1-PP-0042      NaN     1     1     1     1

      A4/5  A4/6  A4/7  A4/8  A4/9
1066     0     0     1     0     0
1068     0     0     0     0     1
1069     0     0     0     0     1
1072     1     1     0     1     0
DEM1-PP-0042
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 4}
DEM1-PP-0042 is not completed! or ERROR

              SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
720  2026-01-12 08:10:02.704  DEM1-PP-0041      NaN     0     0     0     0
721  2026-01-12 08:01:28.231  DEM1-PP-0041      NaN     0     0     0     0
732  2026-01-12 04:15:30.989  DEM1-PP-0041      NaN     0     0     0     0
1031 2025-12-09 01:35:24.885  DEM1-PP-0041      NaN     0     0     0     0
1073 2025-12-04 02:01:45.048  DEM1-PP-0041      NaN     1     1     1     1

      A4/5  A4/6  A4/7  A4/8  A4/9
720      0     0     0     0     1
721      0     0     0     0     1
732      0     0     0     0     1
1031     0     0     1     0     0
1073     1     1     0     1     0
DEM1-PP-0041
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 3, 'Record in A1': 5}
DEM1-PP-0041 is not completed! or ERROR

              SubmissionDate            A1      A1manual  A4/1  A4/2  A4/3  \
1008 2025-12-10 08:26:00.965  DEM1-PP-0034           NaN     0     0     0
1106 2025-12-02 02:51:47.505  DEM1-PP-0034           NaN     1     1     1
1107 2025-12-02 02:49:18.569  DEM1-PP-0034           NaN     0     0     0
1172 2025-11-20 08:52:53.362  DEM1-PP-0034  DEM1-PP-0034     1     1     1

      A4/4  A4/5  A4/6  A4/7  A4/8  A4/9
1008     0     0     0     1     0     0
1106     1     1     1     0     1     0
1107     0     0     0     0     0     1
1172     1     1     1     1     1     0
DEM1-PP-0034
{'A4/1': 2, 'A4/2': 2, 'A4/3': 2, 'A4/4': 2, 'A4/5': 2, 'A4/6': 2, 'A4/7': 2, 'A4/8': 2, 'A4/9': 1, 'Record in A1': 4}
DEM1-PP-0034 is not completed! or ERROR

              SubmissionDate            A1      A1manual  A4/1  A4/2  A4/3  \
558  2026-02-02 06:02:42.198  DEM1-PP-0020  DEM1-PP-0020     0     0     0
983  2025-12-12 04:28:39.704  DEM1-PP-0020           NaN     0     0     0
1124 2025-11-28 04:30:55.187  DEM1-PP-0020           NaN     1     1     1
1129 2025-11-28 02:47:30.880  DEM1-PP-0020           NaN     0     0     0

      A4/4  A4/5  A4/6  A4/7  A4/8  A4/9
558      0     0     0     1     0     0
983      0     0     0     1     0     0
1124     1     1     1     0     1     0
1129     0     0     0     0     0     1
DEM1-PP-0020
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 2, 'A4/8': 1, 'A4/9': 1, 'Record in A1': 4}
DEM1-PP-0020 is not completed! or ERROR

              SubmissionDate            A1 A1manual  A4/1  A4/2  A4/3  A4/4  \
1070 2025-12-04 03:27:58.291  DEM1-PP-0011      NaN     0     0     0     0
1074 2025-12-04 01:32:08.222  DEM1-PP-0011      NaN     0     0     0     0
1147 2025-11-26 07:11:14.903  DEM1-PP-0011      NaN     1     1     1     1
1151 2025-11-26 02:27:21.662  DEM1-PP-0011      NaN     0     0     0     0

      A4/5  A4/6  A4/7  A4/8  A4/9
1070     0     0     1     0     0
1074     0     0     1     0     0
1147     1     1     0     1     0
1151     0     0     0     0     1
DEM1-PP-0011
{'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 2, 'A4/8': 1, 'A4/9': 1, 'Record in A1': 4}
DEM1-PP-0011 is not completed! or ERROR

Empty DataFrame
Columns: [SubmissionDate, A1, A1manual, A4/1, A4/2, A4/3, A4/4, A4/5, A4/6, A4/7, A4/8, A4/9]
Index: []
DEM1-PP-9001

In [28]:
data = result_dict   # your JSON dictionary
print(data)

df = pd.DataFrame.from_dict(data, orient='index').reset_index()
df = df.rename(columns={'index':'ID'})
df['Remark'] = ""
df

{'DEM1-SR-0151': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}, 'DEM1-SR-0156': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}, 'DEM1-PP-0392': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}, 'DEM1-PP-0391': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}, 'DEM1-PP-0383': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-0389': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-0382': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-0381': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}, 'DEM1-PP-0380': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}, 'DEM1-PP-0378': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-0377': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-0372': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}, 'DEM1-PP-0369': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}, 'DEM1-PP-0368': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 1, 'Record in A1': 1}, 'DEM1-PP-0367': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-0364': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-SR-0103': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-SR-0096': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}, 'DEM1-PP-0360': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-0359': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-0352': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}, 'DEM1-PP-0345': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM2-SR-0002': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}, 'DEM1-PP-0310': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-9002': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}, 'DEM1-PP-0220': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}, 'DEM1-PP-0219': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}, 'DEM1-PP-0212': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 0, 'Record in A1': 1}, 'DEM1-PP-0206': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}, 'DEM1-PP-0182': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}, 'DEM1-PP-0119': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}, 'DEM1-PP-0090': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 3, 'Record in A1': 5}, 'DEM1-PP-0049': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 3, 'Record in A1': 5}, 'DEM1-PP-0045': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 0, 'A4/8': 1, 'A4/9': 1, 'Record in A1': 2}, 'DEM1-PP-0042': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 4}, 'DEM1-PP-0041': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 3, 'Record in A1': 5}, 'DEM1-PP-0034': {'A4/1': 2, 'A4/2': 2, 'A4/3': 2, 'A4/4': 2, 'A4/5': 2, 'A4/6': 2, 'A4/7': 2, 'A4/8': 2, 'A4/9': 1, 'Record in A1': 4}, 'DEM1-PP-0020': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 2, 'A4/8': 1, 'A4/9': 1, 'Record in A1': 4}, 'DEM1-PP-0011': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 2, 'A4/8': 1, 'A4/9': 1, 'Record in A1': 4}, 'DEM1-PP-9001': {'A4/1': 0, 'A4/2': 0, 'A4/3': 0, 'A4/4': 0, 'A4/5': 0, 'A4/6': 0, 'A4/7': 0, 'A4/8': 0, 'A4/9': 0, 'Record in A1': 0}, 'DEM1-PP-0004': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 4}, 'DEM1-PP-0003': {'A4/1': 1, 'A4/2': 1, 'A4/3': 1, 'A4/4': 1, 'A4/5': 1, 'A4/6': 1, 'A4/7': 1, 'A4/8': 1, 'A4/9': 2, 'Record in A1': 3}}

,ID,A4/1,A4/2,A4/3,A4/4,A4/5,A4/6,A4/7,A4/8,A4/9,Record in A1,Remark
0,DEM1-SR-0151,0,0,0,0,0,0,0,0,1,1,
1,DEM1-SR-0156,0,0,0,0,0,0,0,0,1,1,
2,DEM1-PP-0392,0,0,0,0,0,0,0,0,0,0,
3,DEM1-PP-0391,0,0,0,0,0,0,0,0,0,0,
4,DEM1-PP-0383,1,1,1,1,1,1,1,1,0,1,
5,DEM1-PP-0389,1,1,1,1,1,1,1,1,0,1,
6,DEM1-PP-0382,1,1,1,1,1,1,1,1,0,1,
7,DEM1-PP-0381,0,0,0,0,0,0,0,0,0,0,
8,DEM1-PP-0380,0,0,0,0,0,0,0,0,1,1,
9,DEM1-PP-0378,1,1,1,1,1,1,1,1,0,1,
10,DEM1-PP-0377,1,1,1,1,1,1,1,1,0,1,
11,DEM1-PP-0372,0,0,0,0,0,0,0,0,1,1,
12,DEM1-PP-0369,0,0,0,0,0,0,0,0,0,0,
13,DEM1-PP-0368,0,0,0,0,0,0,0,0,1,1,
14,DEM1-PP-0367,1,1,1,1,1,1,1,1,0,1,
15,DEM1-PP-0364,1,1,1,1,1,1,1,1,0,1,
16,DEM1-SR-0103,1,1,1,1,1,1,1,1,0,1,
17,DEM1-SR-0096,1,1,1,1,1,1,1,1,2,3,
18,DEM1-PP-0360,1,1,1,1,1,1,1,1,0,1,
19,DEM1-PP-0359,1,1,1,1,1,1,1,1,0,1,
20,DEM1-PP-0352,1,1,1,1,1,1,1,1,2,3,
21,DEM1-PP-0345,1,1,1,1,1,1,1,1,0,1,
22,DEM2-SR-0002,0,0,0,0,0,0,0,0,0,0,
23,DEM1-PP-0310,1,1,1,1,1,1,1,1,0,1,
24,DEM1-PP-9002,0,0,0,0,0,0,0,0,0,0,
25,DEM1-PP-0220,1,1,1,1,1,1,1,1,2,3,
26,DEM1-PP-0219,1,1,1,1,1,1,1,1,2,3,
27,DEM1-PP-0212,1,1,1,1,1,1,1,1,0,1,
28,DEM1-PP-0206,1,1,1,1,1,1,1,1,2,3,
29,DEM1-PP-0182,1,1,1,1,1,1,1,1,2,3,
30,DEM1-PP-0119,1,1,1,1,1,1,1,1,2,3,
31,DEM1-PP-0090,1,1,1,1,1,1,1,1,3,5,
32,DEM1-PP-0049,1,1,1,1,1,1,1,1,3,5,
33,DEM1-PP-0045,1,1,1,1,1,1,0,1,1,2,
34,DEM1-PP-0042,1,1,1,1,1,1,1,1,2,4,
35,DEM1-PP-0041,1,1,1,1,1,1,1,1,3,5,
36,DEM1-PP-0034,2,2,2,2,2,2,2,2,1,4,
37,DEM1-PP-0020,1,1,1,1,1,1,2,1,1,4,
38,DEM1-PP-0011,1,1,1,1,1,1,2,1,1,4,
39,DEM1-PP-9001,0,0,0,0,0,0,0,0,0,0,
40,DEM1-PP-0004,1,1,1,1,1,1,1,1,2,4,
41,DEM1-PP-0003,1,1,1,1,1,1,1,1,2,3,

In [29]:
A4_cols = [f'A4/{i}' for i in range(1,10)]
df['A4_max'] = df[A4_cols].max(axis=1)

## Set up Remark Column

In [30]:
df['Remark'] = np.select(
    [
        df['A4_max'] == 0,
        df['A4_max'] == 2,
        df['A4_max'] == 3,
        df['A4_max'] > 3
    ],
    [
        "All Missing",
        "Double Entry",
        "Triple Entry",
        "More Than 3 Entry"
    ],
    default=""
)

df

,ID,A4/1,A4/2,A4/3,A4/4,A4/5,A4/6,A4/7,A4/8,A4/9,Record in A1,Remark,A4_max
0,DEM1-SR-0151,0,0,0,0,0,0,0,0,1,1,,1
1,DEM1-SR-0156,0,0,0,0,0,0,0,0,1,1,,1
2,DEM1-PP-0392,0,0,0,0,0,0,0,0,0,0,All Missing,0
3,DEM1-PP-0391,0,0,0,0,0,0,0,0,0,0,All Missing,0
4,DEM1-PP-0383,1,1,1,1,1,1,1,1,0,1,,1
5,DEM1-PP-0389,1,1,1,1,1,1,1,1,0,1,,1
6,DEM1-PP-0382,1,1,1,1,1,1,1,1,0,1,,1
7,DEM1-PP-0381,0,0,0,0,0,0,0,0,0,0,All Missing,0
8,DEM1-PP-0380,0,0,0,0,0,0,0,0,1,1,,1
9,DEM1-PP-0378,1,1,1,1,1,1,1,1,0,1,,1
10,DEM1-PP-0377,1,1,1,1,1,1,1,1,0,1,,1
11,DEM1-PP-0372,0,0,0,0,0,0,0,0,1,1,,1
12,DEM1-PP-0369,0,0,0,0,0,0,0,0,0,0,All Missing,0
13,DEM1-PP-0368,0,0,0,0,0,0,0,0,1,1,,1
14,DEM1-PP-0367,1,1,1,1,1,1,1,1,0,1,,1
15,DEM1-PP-0364,1,1,1,1,1,1,1,1,0,1,,1
16,DEM1-SR-0103,1,1,1,1,1,1,1,1,0,1,,1
17,DEM1-SR-0096,1,1,1,1,1,1,1,1,2,3,Double Entry,2
18,DEM1-PP-0360,1,1,1,1,1,1,1,1,0,1,,1
19,DEM1-PP-0359,1,1,1,1,1,1,1,1,0,1,,1
20,DEM1-PP-0352,1,1,1,1,1,1,1,1,2,3,Double Entry,2
21,DEM1-PP-0345,1,1,1,1,1,1,1,1,0,1,,1
22,DEM2-SR-0002,0,0,0,0,0,0,0,0,0,0,All Missing,0
23,DEM1-PP-0310,1,1,1,1,1,1,1,1,0,1,,1
24,DEM1-PP-9002,0,0,0,0,0,0,0,0,0,0,All Missing,0
25,DEM1-PP-0220,1,1,1,1,1,1,1,1,2,3,Double Entry,2
26,DEM1-PP-0219,1,1,1,1,1,1,1,1,2,3,Double Entry,2
27,DEM1-PP-0212,1,1,1,1,1,1,1,1,0,1,,1
28,DEM1-PP-0206,1,1,1,1,1,1,1,1,2,3,Double Entry,2
29,DEM1-PP-0182,1,1,1,1,1,1,1,1,2,3,Double Entry,2
30,DEM1-PP-0119,1,1,1,1,1,1,1,1,2,3,Double Entry,2
31,DEM1-PP-0090,1,1,1,1,1,1,1,1,3,5,Triple Entry,3
32,DEM1-PP-0049,1,1,1,1,1,1,1,1,3,5,Triple Entry,3
33,DEM1-PP-0045,1,1,1,1,1,1,0,1,1,2,,1
34,DEM1-PP-0042,1,1,1,1,1,1,1,1,2,4,Double Entry,2
35,DEM1-PP-0041,1,1,1,1,1,1,1,1,3,5,Triple Entry,3
36,DEM1-PP-0034,2,2,2,2,2,2,2,2,1,4,Double Entry,2
37,DEM1-PP-0020,1,1,1,1,1,1,2,1,1,4,Double Entry,2
38,DEM1-PP-0011,1,1,1,1,1,1,2,1,1,4,Double Entry,2
39,DEM1-PP-9001,0,0,0,0,0,0,0,0,0,0,All Missing,0
40,DEM1-PP-0004,1,1,1,1,1,1,1,1,2,4,Double Entry,2
41,DEM1-PP-0003,1,1,1,1,1,1,1,1,2,3,Double Entry,2

In [31]:
df.replace({0: 'Missing'}, inplace=True)
df.drop(columns=['A4_max'], inplace=True) # drop column A4_max
df

,ID,A4/1,A4/2,A4/3,A4/4,A4/5,A4/6,A4/7,A4/8,A4/9,Record in A1,Remark
0,DEM1-SR-0151,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
1,DEM1-SR-0156,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
2,DEM1-PP-0392,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
3,DEM1-PP-0391,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
4,DEM1-PP-0383,1,1,1,1,1,1,1,1,Missing,1,
5,DEM1-PP-0389,1,1,1,1,1,1,1,1,Missing,1,
6,DEM1-PP-0382,1,1,1,1,1,1,1,1,Missing,1,
7,DEM1-PP-0381,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
8,DEM1-PP-0380,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
9,DEM1-PP-0378,1,1,1,1,1,1,1,1,Missing,1,
10,DEM1-PP-0377,1,1,1,1,1,1,1,1,Missing,1,
11,DEM1-PP-0372,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
12,DEM1-PP-0369,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
13,DEM1-PP-0368,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
14,DEM1-PP-0367,1,1,1,1,1,1,1,1,Missing,1,
15,DEM1-PP-0364,1,1,1,1,1,1,1,1,Missing,1,
16,DEM1-SR-0103,1,1,1,1,1,1,1,1,Missing,1,
17,DEM1-SR-0096,1,1,1,1,1,1,1,1,2,3,Double Entry
18,DEM1-PP-0360,1,1,1,1,1,1,1,1,Missing,1,
19,DEM1-PP-0359,1,1,1,1,1,1,1,1,Missing,1,
20,DEM1-PP-0352,1,1,1,1,1,1,1,1,2,3,Double Entry
21,DEM1-PP-0345,1,1,1,1,1,1,1,1,Missing,1,
22,DEM2-SR-0002,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
23,DEM1-PP-0310,1,1,1,1,1,1,1,1,Missing,1,
24,DEM1-PP-9002,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
25,DEM1-PP-0220,1,1,1,1,1,1,1,1,2,3,Double Entry
26,DEM1-PP-0219,1,1,1,1,1,1,1,1,2,3,Double Entry
27,DEM1-PP-0212,1,1,1,1,1,1,1,1,Missing,1,
28,DEM1-PP-0206,1,1,1,1,1,1,1,1,2,3,Double Entry
29,DEM1-PP-0182,1,1,1,1,1,1,1,1,2,3,Double Entry
30,DEM1-PP-0119,1,1,1,1,1,1,1,1,2,3,Double Entry
31,DEM1-PP-0090,1,1,1,1,1,1,1,1,3,5,Triple Entry
32,DEM1-PP-0049,1,1,1,1,1,1,1,1,3,5,Triple Entry
33,DEM1-PP-0045,1,1,1,1,1,1,Missing,1,1,2,
34,DEM1-PP-0042,1,1,1,1,1,1,1,1,2,4,Double Entry
35,DEM1-PP-0041,1,1,1,1,1,1,1,1,3,5,Triple Entry
36,DEM1-PP-0034,2,2,2,2,2,2,2,2,1,4,Double Entry
37,DEM1-PP-0020,1,1,1,1,1,1,2,1,1,4,Double Entry
38,DEM1-PP-0011,1,1,1,1,1,1,2,1,1,4,Double Entry
39,DEM1-PP-9001,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
40,DEM1-PP-0004,1,1,1,1,1,1,1,1,2,4,Double Entry
41,DEM1-PP-0003,1,1,1,1,1,1,1,1,2,3,Double Entry

## A1D1 - All - Missing Information Checking

In [32]:
df = df.rename(columns=a4_section_mapping)
df

,A1,B. Inclusion Criteria - A4/1,C. Demographic Information - A4/2,D. Animal Contact - A4/3,E. Mosquito Activity Information - A4/4,F. General Knowledge - A4/5,G. Child Information - A4/6,H. Chile Vaccination Record - A4/7,I. Child Medical History - A4/8,J. Physical Examination and Neurological Assessment - A4/9,Record in A1,Remark
0,DEM1-SR-0151,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
1,DEM1-SR-0156,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
2,DEM1-PP-0392,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
3,DEM1-PP-0391,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
4,DEM1-PP-0383,1,1,1,1,1,1,1,1,Missing,1,
5,DEM1-PP-0389,1,1,1,1,1,1,1,1,Missing,1,
6,DEM1-PP-0382,1,1,1,1,1,1,1,1,Missing,1,
7,DEM1-PP-0381,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
8,DEM1-PP-0380,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
9,DEM1-PP-0378,1,1,1,1,1,1,1,1,Missing,1,
10,DEM1-PP-0377,1,1,1,1,1,1,1,1,Missing,1,
11,DEM1-PP-0372,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
12,DEM1-PP-0369,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
13,DEM1-PP-0368,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
14,DEM1-PP-0367,1,1,1,1,1,1,1,1,Missing,1,
15,DEM1-PP-0364,1,1,1,1,1,1,1,1,Missing,1,
16,DEM1-SR-0103,1,1,1,1,1,1,1,1,Missing,1,
17,DEM1-SR-0096,1,1,1,1,1,1,1,1,2,3,Double Entry
18,DEM1-PP-0360,1,1,1,1,1,1,1,1,Missing,1,
19,DEM1-PP-0359,1,1,1,1,1,1,1,1,Missing,1,
20,DEM1-PP-0352,1,1,1,1,1,1,1,1,2,3,Double Entry
21,DEM1-PP-0345,1,1,1,1,1,1,1,1,Missing,1,
22,DEM2-SR-0002,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
23,DEM1-PP-0310,1,1,1,1,1,1,1,1,Missing,1,
24,DEM1-PP-9002,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
25,DEM1-PP-0220,1,1,1,1,1,1,1,1,2,3,Double Entry
26,DEM1-PP-0219,1,1,1,1,1,1,1,1,2,3,Double Entry
27,DEM1-PP-0212,1,1,1,1,1,1,1,1,Missing,1,
28,DEM1-PP-0206,1,1,1,1,1,1,1,1,2,3,Double Entry
29,DEM1-PP-0182,1,1,1,1,1,1,1,1,2,3,Double Entry
30,DEM1-PP-0119,1,1,1,1,1,1,1,1,2,3,Double Entry
31,DEM1-PP-0090,1,1,1,1,1,1,1,1,3,5,Triple Entry
32,DEM1-PP-0049,1,1,1,1,1,1,1,1,3,5,Triple Entry
33,DEM1-PP-0045,1,1,1,1,1,1,Missing,1,1,2,
34,DEM1-PP-0042,1,1,1,1,1,1,1,1,2,4,Double Entry
35,DEM1-PP-0041,1,1,1,1,1,1,1,1,3,5,Triple Entry
36,DEM1-PP-0034,2,2,2,2,2,2,2,2,1,4,Double Entry
37,DEM1-PP-0020,1,1,1,1,1,1,2,1,1,4,Double Entry
38,DEM1-PP-0011,1,1,1,1,1,1,2,1,1,4,Double Entry
39,DEM1-PP-9001,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
40,DEM1-PP-0004,1,1,1,1,1,1,1,1,2,4,Double Entry
41,DEM1-PP-0003,1,1,1,1,1,1,1,1,2,3,Double Entry

## Get Data - Siem Reap Only

In [33]:
# df_sr = df.query('"SR" in ID')
df_sr = df[df['A1'].str.contains('SR', na=False)]
# df_sr

## Get Data - Phnom Penh Only

In [34]:
df_pp = df[df['A1'].str.contains('PP', na=False)]
# df_pp

## Export all in one excel file

In [35]:
with pd.ExcelWriter('.././result/A1D1_Missing_Information_Checking.xlsx', engine='xlsxwriter') as writer:
    df.to_excel(writer, sheet_name='A1D1_Missing_Info_ALL', index=False)
    df_pp.to_excel(writer, sheet_name='A1D1_Missing_Info_PP', index=False)
    df_sr.to_excel(writer, sheet_name='A1D1_Missing_Info_SR', index=False)

In [36]:
# # Optional: Auto-adjust column width (nice formatting)

# with pd.ExcelWriter('output.xlsx', engine='xlsxwriter') as writer:
#     for name, df in {
#         'A1D1_Missing_Info_ALL': df,
#         'A1D1_Missing_Info_SR': df_pp,
#         'A1D1_Missing_Info_PP': df_sr
#     }.items():
#         df.to_excel(writer, sheet_name=name, index=False)
        
#         worksheet = writer.sheets[name]
#         for i, col in enumerate(df.columns):
#             width = max(df[col].astype(str).map(len).max(), len(col))
#             worksheet.set_column(i, i, width)

In [37]:
df

,A1,B. Inclusion Criteria - A4/1,C. Demographic Information - A4/2,D. Animal Contact - A4/3,E. Mosquito Activity Information - A4/4,F. General Knowledge - A4/5,G. Child Information - A4/6,H. Chile Vaccination Record - A4/7,I. Child Medical History - A4/8,J. Physical Examination and Neurological Assessment - A4/9,Record in A1,Remark
0,DEM1-SR-0151,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
1,DEM1-SR-0156,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
2,DEM1-PP-0392,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
3,DEM1-PP-0391,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
4,DEM1-PP-0383,1,1,1,1,1,1,1,1,Missing,1,
5,DEM1-PP-0389,1,1,1,1,1,1,1,1,Missing,1,
6,DEM1-PP-0382,1,1,1,1,1,1,1,1,Missing,1,
7,DEM1-PP-0381,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
8,DEM1-PP-0380,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
9,DEM1-PP-0378,1,1,1,1,1,1,1,1,Missing,1,
10,DEM1-PP-0377,1,1,1,1,1,1,1,1,Missing,1,
11,DEM1-PP-0372,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
12,DEM1-PP-0369,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
13,DEM1-PP-0368,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,1,1,
14,DEM1-PP-0367,1,1,1,1,1,1,1,1,Missing,1,
15,DEM1-PP-0364,1,1,1,1,1,1,1,1,Missing,1,
16,DEM1-SR-0103,1,1,1,1,1,1,1,1,Missing,1,
17,DEM1-SR-0096,1,1,1,1,1,1,1,1,2,3,Double Entry
18,DEM1-PP-0360,1,1,1,1,1,1,1,1,Missing,1,
19,DEM1-PP-0359,1,1,1,1,1,1,1,1,Missing,1,
20,DEM1-PP-0352,1,1,1,1,1,1,1,1,2,3,Double Entry
21,DEM1-PP-0345,1,1,1,1,1,1,1,1,Missing,1,
22,DEM2-SR-0002,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
23,DEM1-PP-0310,1,1,1,1,1,1,1,1,Missing,1,
24,DEM1-PP-9002,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
25,DEM1-PP-0220,1,1,1,1,1,1,1,1,2,3,Double Entry
26,DEM1-PP-0219,1,1,1,1,1,1,1,1,2,3,Double Entry
27,DEM1-PP-0212,1,1,1,1,1,1,1,1,Missing,1,
28,DEM1-PP-0206,1,1,1,1,1,1,1,1,2,3,Double Entry
29,DEM1-PP-0182,1,1,1,1,1,1,1,1,2,3,Double Entry
30,DEM1-PP-0119,1,1,1,1,1,1,1,1,2,3,Double Entry
31,DEM1-PP-0090,1,1,1,1,1,1,1,1,3,5,Triple Entry
32,DEM1-PP-0049,1,1,1,1,1,1,1,1,3,5,Triple Entry
33,DEM1-PP-0045,1,1,1,1,1,1,Missing,1,1,2,
34,DEM1-PP-0042,1,1,1,1,1,1,1,1,2,4,Double Entry
35,DEM1-PP-0041,1,1,1,1,1,1,1,1,3,5,Triple Entry
36,DEM1-PP-0034,2,2,2,2,2,2,2,2,1,4,Double Entry
37,DEM1-PP-0020,1,1,1,1,1,1,2,1,1,4,Double Entry
38,DEM1-PP-0011,1,1,1,1,1,1,2,1,1,4,Double Entry
39,DEM1-PP-9001,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,All Missing
40,DEM1-PP-0004,1,1,1,1,1,1,1,1,2,4,Double Entry
41,DEM1-PP-0003,1,1,1,1,1,1,1,1,2,3,Double Entry

# YData Profiling

In [38]:
# profile = ProfileReport(df, title="Profiling Report")
# profile